### ISSUE TITLE
Cannot Import X-Plane object files: Addon: "Import & Export: X-Plane"

### ISSUE THREAD

**Issue by lpanse** [der-On/XPlane2Blender#100]
How can I import an x-plane scenery file (.obj)?

File > Import > ???
File > Export > XPlane Object (.obj)

Folder Installation: io_xplane2blender:

C:\Users<user>\AppData\Roaming\Blender Foundation\Blender\2.65\scripts\addons\

Addon: 
Version 3.2 beta

System:
Win 7 32bit
Python: 3.1
Blender: 2.65

Regards

**Comment by Rocketflyer360** [comment]
I'm trying to install it but it's saying that "ktmutil is not a valid file". I'm using windows 8, is there anything I can do?

**Comment by der-On** [comment]
I'm sorry but I cannot provide support for Windows 8. A quick search for "ktmutil" told me, that it is a windows 8 system file. Maybe your windows installation is corrupt/broken or you are missing this file?

**Comment by tngreene** [comment]
See also #148 (except for the tech support stuff at the end.)
