### ISSUE TITLE
Bone animations are off

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#108]
By the "the animation is off" I meant it doesn't move by the axis I made it rotate on when I open it in X-Plane.

How I caused this:
I think it's because I assigned rotation to all three axis. The aileron and the canopy animation have the animation set on all of the three axis.

In Blender, make a plane, make it look like an aileron and then rotate it like this:
kf0 x 0° | y 0° | z 0°
kf1 x 30° | y -4.1° | z 0.25°
kf2 x -30° | y 3.8° | z 1.5°

Also make another plane so you have it as a reference on how the aileron moves in blender and how it moves in plane-maker (to see the difference).

**Comment by tngreene** [comment]
Closing due to being unable to replicate it, and because the animation code has gone through a lot of fixes since 2013.
