### ISSUE TITLE
automated regression and unit tests

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#120]

**Comment by der-On** [comment]
Executing automated tests should be simple using pythons `unittest` module. It provides assertions.

We can simply create a range of blend files and python scripts that run assertions on them and execute those together using blenders CLI:

`blender -b some.blend --python some.py`

This will open `some.blend` and execute `some.py` once it's loaded.

However in current blender versions the CLIs arg parsing seems to be broken. I [filed a bug](https://developer.blender.org/T44764).

**Comment by der-On** [comment]
@bsupnik just assigned you to this, so you get notified. Assign it back to me after reading.

**Comment by der-On** [comment]
Actually the call to `unittest.main()` within the script caused the arg parsing problems. Need to find out how to run the tests other then using `unittest.main()`

**Comment by der-On** [comment]
Work has started in a seperate Branch: [E-120-automated-tests](https://github.com/der-On/XPlane2Blender/tree/E-120-automated-tests)

**Comment by bsupnik** [comment]
Cool - this seems like a good match for what we want.
