### ISSUE TITLE
Combined loc+rotate key frame on armature-bone animation produces wrong output

### ISSUE THREAD

**Issue by bsupnik** [der-On/XPlane2Blender#126]
This is a bug Alex Unruh and I found while testing armature-based animation:

A single armature/bone animation that both translates and rotates produces wrong output in the current script.

For example: a rotation around the X axis and translation around the Z axis should produce a model that moves up and down linearly while rotating around the translated point.

The actual output is opposite: the rotation affects the axis of translation, which gets written to disk with its higher key frames matching the rotation - in our case a diagonal rotation.

The bug appears to be in xplane_types.py line 644:

```
        matrix = rot.to_matrix().to_4x4()*Matrix.Translation(loc)
```

This code is reconstructing the bone's transform, but is doing so backward; the correct code is

```
        matrix = Matrix.Translation(loc) * rot.to_matrix().to_4x4()
```

It is possible that with the correction, the whole logic could be simplified, since the reconstructed matrix should match the original.

**Comment by der-On** [comment]
Wow thanks. Could you please provide a pull request and test it locally?

I'm sorry not to have regression tests implemented yet.

**Comment by bsupnik** [comment]
Sure but let me look at bug 127 a bit more first.  My goal is to create a series of animation test cases that cover all bases; even if they aren't automatically regressed, we'd at least have a way of knowing whether we introduced new bugs.

The changes for 127 may be quite a bit more invasive; I'm still investigating all of the cases.

**Comment by bsupnik** [comment]
https://github.com/der-On/XPlane2Blender/wiki/Proposed-redesign-of-animation-export

I think this is what we need to actually fix all of the animation issues, rather than just trimming around the edges of the problem.

The fact that the animation OBJ8 code is output -without- contextual information about the -source- of the animation is the fundamental major design problem.  It is why so many of the object-based animations produce wrong output.  For example, the user can change the Euler order in their OBJ animation and the information is not currently visible to the exporter.

**Comment by der-On** [comment]
@bsupnik Ben! It's you. I was in a hurry, not red your nick. Lol! Great to have you in here actively.

**Comment by bsupnik** [comment]
Yep, it's me. :-) I spent about one full day carefully going over the animation code - the wiki notes are sort of the result.  Ping me directly to sync up on where we go next...

**Comment by der-On** [comment]
Just a test

**Comment by tngreene** [comment]
Now that we have made several improvements to the animation algorithm, is this still relevant?

**Comment by bsupnik** [comment]
This is complete by the 3.3 rewrite of animation and 3.4 debug of animation.
