### ISSUE TITLE
Rework Material Export

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#139]
See https://github.com/der-On/XPlane2Blender/wiki/Material-and-Instancing-Model and https://github.com/der-On/XPlane2Blender/wiki/Material-Property-Matrix for more detailes.

**Comment by BlueishGhost** [comment]
Where are the errors logged?

**Comment by der-On** [comment]
@BlueishGhost Errors are logged to an internal text file now. User gets notified about them after export.
