### ISSUE TITLE
Multi axis decompile issues

### ISSUE THREAD

**Issue by alxunru** [der-On/XPlane2Blender#144]
Comparing the 2.7 script output to the 2.49 script output, we are still having issues decompiling the multi axis case (that works in 2.49). Ben and I have gone through and run a number of different tests (including changing axis order in the python scripts) and ultimately set the rest pose axis of the armature to blender's default (-y) axis to attempt to isolate the issue.

The 2.49 output was the expected keyframed output as assigned in Blender.

https://www.dropbox.com/s/r7mqevsi03mnfko/monkey_test.zip?dl=0

Talk with Ben RE the issue as I think he has a better grasp of it than I do.

**Comment by alxunru** [comment]
2.49 blend file

https://www.dropbox.com/s/io152vsvqkcxaz7/monkey249.blend.zip?dl=0

**Comment by der-On** [comment]
@bsupnik I've now added the monkey test case.

You can run it using `python tests.py --filter monkey` or `python tests.py --filter monkey --debug` to get verbose debuging output.

**Comment by der-On** [comment]
I've now updated all fixtures and manually checked them for validity also.
