### ISSUE TITLE
Vertex Coordinates rounding error

### ISSUE THREAD

**Issue by airfightergr** [der-On/XPlane2Blender#147]
Note: I'm not sure if this might be a blender/python limitation.

I'm editing the mesh with blender. The source object (part of the mesh) comes from MeshRemexe as X-Plane's .obj. I'm importing it to blender with the blender2.49b/Xplane2Blender3.10, and then I edit it in blender 2.76 and exporting it with the latest script.

I get gaps in the perimeter of the edited part. The reason is that the vertices look like this: 
VT	-8794056.00000000	201.81651306	-4197771.50000000	-0.04362203	0.99903011	-0.00598734	0.07698531	0.81265795
All the lat/lon vertices are rounded to the closest 0.0 or 0.5. Exporting the same part with the mesh with sketchup, I get no gaps and the vertices look like this:
VT	-8792170.6912  202.4374 -4197249.3706	 0.004  1.000  0.003	 0.3120  0.7024

Any thoughts?

**Comment by der-On** [comment]
@airfightergr Are you getting the gaps after import using blender 2.49b? XPlane2Blender 3.2 (blender 2.7) does export with a decimal precision of 6.

**Comment by airfightergr** [comment]
Yes, first importing with blender 2.49 and then using blender 2.76/X2B3.2. That's why I asked Ben in developers blog about importing X-Plane objects, to avoid 2.49 part.

Another clue, probably is a blender limitation. Does blender (even 64-bit .. 2.76) stores those values in 32-bit? Could this be the problem?

**Comment by der-On** [comment]
The blender 2.49 import does the rounding I think. The 32bit limitation of numbers is no problem for the values you mentioned. It get's problematic for really large values that need a **lot** of decimals.

The demand for an importer seems to come up all the time in the community. We really have to consider implemeting it. But it's a huge task and will not be able to import everything.

**Comment by airfightergr** [comment]
The importer, since the MeshRemexe tool (http://forums.x-plane.org/index.php?app=downloads&showfile=29153) became available, I think now has much more significant role. Taking the airport mesh into blender and editing it is now very easy and the ability to create complex stuff will promote the overall X-Plane's addon quality.

And the importer does not need to import very complex stuff. Importing just the geometry right is more than enough. And will happy to beta test it day 1 you will have something (sound desperate? I am!)

What I would like to exclude is that export script has nothing to do with that problem.By ruling one by one the factors, I'm trying to pinpoint the problem. So, if export script is irrelevant, then please close this one.

Thanks

**Comment by der-On** [comment]
Thank you. I'm closing this now.

I'll try to write down a draft/specification for the importer soon.
