### ISSUE TITLE
New 1050-compatible manipulators

### ISSUE THREAD

**Issue by bsupnik** [der-On/XPlane2Blender#149]
Command knob manipulators
---------------------------------------
    ATTR_manip_command_knob <cursor> <positive cmnd> <negative cmnd> <tool tip>
    ATTR_manip_command_switch_up_down <cursor> <positive cmnd> <negative cmnd> <tool tip>
    ATTR_manip_command_switch_left_right <cursor> <positive cmnd> <negative cmnd> <tool tip>

These form a new manipulator that represents a real world rotary knob or multi-position switch.  The manip type specifies how the real-world mechanism works. Parameters:
* cursor - a standard cursor enumeration when the mouse is over the dataref.
* positive command - command that is run once each time the manipulator is incremented a notch.
* negative command - command that is run once each time the manipulator is decremented a notch.
* tool tip - a string that is shown when tool tips are enabled and the mouse is held over the manipulator.
The assumption is that positive cmnd and negative cmnd are opposites, e.g.
    sim/radios/obs_HSI_down
    sim/radios/obs_HSI_up

Dataref knob manipulators
------------------------------------
    ATTR_manip_axis_switch_left_right <cursor>  <v1> <v2> <click step> <hold step> <dref> <tool tip>
    ATTR_manip_axis_switch_up_down <cursor>  <v1> <v2> <click step> <hold step> <dref> <tool tip>
    ATTR_manip_axis_switch_left_right <cursor>  <v1> <v2> <click step> <hold step> <dref> <tool tip>

These form a new manipulator that also represents a real world mechanism, but is used when no command is available.
* cursor - a standard cursor enumeration for when the mouse is held over the manipulator.
* v1 and v2 - floating point values for the min and max range of the dataref.
* click step - the amount the dataref increases or decreases when the manpulator is single-clicked.
* hold step - the amount the dataref increases or decreases per second if the mouse is held down.
* dref - the dataref name to change
* tool tip - a string that is shown when tool tips are enabled and the mouse is held over the manipulator.
The intention is that _one_ of click-step and hold-step will be 0, e.g. for the HSI mode knob, click step might be 1 and hold-step 0 so each click moves the HSI mode knob and then does nothing until the user re-clicks, for precision.  For a lighting rheostat,click might be 0 and hold might be 0.25 so that it takes four seconds of holding to dim the lights.

    ATTR_manip_wheel <delta>

This comes -after- some dataref-based manipulator and specifies the increment/decrement of the dataref for each mouse wheel tick.  Dleta is a floating point value.  This is legal on these manipulators:

ATTR_manip_drag_axis, ATTR_manip_push, ATTR_manip_radio, ATTR_manip_toggle, ATTR_manip_delta, ATTR_manip_wrap, ATTR_manip_drag_axis_pix.

**Comment by der-On** [comment]
@bsupnik is `ATTR_manip_wheel` different from the regular attributes by not appyling to subsequent manipulator commands but only to the directly preceding one?

**Comment by bsupnik** [comment]
Yes - this is correct - ATTR_manip_wheel affects the -previous- manipulator
and it is illegal to have it BEFORE any manipulators.

It is a one-off (not latched) - you need a separate ATTR_manip_wheel for EACH manipulator that has one.
