### ISSUE TITLE
Objects in multiple layers do not get exported.

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#150]

**Comment by tngreene** [comment]
Is there an error message that goes with this?

**Comment by tngreene** [comment]
I just tried making a simple scene: 1 cube, in its relations panel I have it set to be part of layer 1 and 2. In the scene settings I made sure layer 1 (call 1) and layer 2 (called 2) were set to export, and that in the Blender GUI, both layers were visible.

On export it exported two identical obj files with no errors or unexpected warnings.

Is there anything more you can tell me about how to reproduce this problem?

**Comment by cpuwolf** [comment]
XPlane2Blender 3.5.0-rc.1+40.20181016150257

layers mode doesnt work, only first layer is exported

**Comment by tngreene** [comment]
Are the other layers you want to export also visible with objects in them?

**Comment by cpuwolf** [comment]
yes, I plan to export the cockpit obj in layer 2, but I failed. did I miss the concept here?

**Comment by airfightergr** [comment]
1. Is the layer 2 visible during export?
2. Do you have set up correctly the export properties in the scene panel?
3. Do you get any errors in the log file?
