### ISSUE TITLE
Auto Detect textures feature, draped polys not working latest build

### ISSUE THREAD

**Issue by alxunru** [der-On/XPlane2Blender#152]
Ondrej,

Attached are a couple test cases. For the first issue, use testAutoDetect.blend.
Having gone through the process to set up the materials, assign UV space, and assign textures in the material editor, the auto detect feature is killing the export. Manually selecting the textures seems to work.

There are a couple other issues that I have run into.
Draped polygons are killing export (see Test.blend test case).
"'material in object "Plane" must not be draped" is the error in the log output.

And finally, error logging in the xplane2blender.log file isn't robust yet. I see errors pop up in the log entry only occasionally. This doesn't help content developers isolate issues.

The files:
[BlenderTests.zip](https://github.com/der-On/XPlane2Blender/files/94874/BlenderTests.zip)

Its possible that i've got something screwy in my set up. If its my end, we should include some gotchas in the documentation because I don't feel that I've done anything illogical or out of the ordinary.

Cheers

Alex

**Comment by der-On** [comment]
@alxunru thank you. I'll be to work on this tomorrow.
