### ISSUE TITLE
More material bugs

### ISSUE THREAD

**Issue by alxunru** [der-On/XPlane2Blender#153]
We've still got a few material bugs kicking around.
Here's what I managed to isolate with the fresh scripts.

For these cases
2 incompatible draped materials 
where 3 materials are used including
• non draped tex A
• draped tex A
• draped tex B

The expected result is a failure as both tex A and B cannot be used for draping.
The test does fail, but no reason is given for the failure.

The same is true with the other 2 incompatible draped materials test where the 3 materials used are 
• non-draped tex A, spec 1.0
• draped tex B, spec 0.5
• draped tex B, spec 0.7

It fails as expected, but as above, no reason for the failure is given. These test case under blend file DRAPED_Fail.blend utilizing layers 1 and 2 for the export.

For instanced scenery objects, I get a python error on export.

<img width="841" alt="screen shot 2016-01-25 at 12 37 08 pm" src="https://cloud.githubusercontent.com/assets/14224727/12562586/3f8e3030-c363-11e5-9933-0edfd180c567.png">

The blend file for instanced objects is INSTANCED.blend

Because of this, I am unable to run the instanced tests because nothing will export. If there is an 'override specularity' setting in the UI that is required for instancing, I can't find it.

Lastly, exports for aircraft parts that involve the cockpit object are failing export because the cockpit panel texture is seen as illegal when it shouldn't be.
The blend file for this case is COCKPIT.blend.

[BlendFiles.zip](https://github.com/der-On/XPlane2Blender/files/103890/BlendFiles.zip)

I've also been trying to get the LIT texture previews to show up. What render mode do I need to be in for them to be visible? The instanced.blend is set up with a LIT texture assigned where it needs to be.

**Comment by alxunru** [comment]
You may be able to ignore the cockpit.blend issue. I just went back on a hunch and had some user error. Double checking everything now

**Comment by alxunru** [comment]
We're still failing the cockpit object test (I had set the object export mode to aircraft originally, not cockpit mode)

Here is the error.
ERROR: Material in object "Cube.001" Texture must be //texture.png..
ERROR: Material in object "Cube" Texture must be //../cockpit/-PANELS-/panel.png..

Cube.001 is the cube where the panel texture / material is applied
Cube is the cube with a standard material applied.

[COCKPIT.blend.zip](https://github.com/der-On/XPlane2Blender/files/103960/COCKPIT.blend.zip)

**Comment by der-On** [comment]
@alxunru The Draped_fail.blend had one minor user error:

- Export for Layer 1 was not enabled
- and you have to activate the layers you want to export. (inactive layers will not be exported, this is actually a feature)

The rest is now fixed. Thanks for the files and report.
