### ISSUE TITLE
Plugin quits exporting!

### ISSUE THREAD

**Issue by alxunru** [der-On/XPlane2Blender#154]
So during my trials with intentionally failing exports / bug hunting, I've noticed that a good percentage of the time, after failing an export (typically an export that doesn't write an error out to the internal log file), that something in the plugin doesn't 'reset' and I'm left with exports that should be legal failing without leaving any errors in the log file. I'm able to save my blend file, quit blender, restart, and make a good export having done nothing else but restarting.

If I can find a way to consistently reproduce the steps to get to this point, I'll amend this posting.
As of right now, it is something that crops up after I've been messing with things for a while.

**Comment by der-On** [comment]
@alxunru Thanks for your report. Could you please send/append a file where this happens. I can write a test-case that exports it twice and then start to debug it.

**Comment by alxunru** [comment]
On it

**Comment by der-On** [comment]
@alxunru is this still relevant?
