### ISSUE TITLE
Animated objects are invisible in planemaker

### ISSUE THREAD

**Issue by DevLKAircrafts** [der-On/XPlane2Blender#155]
Hello,

The parts that I have animated in Blender are invisible in planemaker. I added this dataref to the bone (in pose mode): sim/aircraft/parts/acf_rudd2

pic: http://i.imgur.com/qJVyjxl.png

**Comment by der-On** [comment]
@DevLKAircrafts Please attach the blender file, otherwhise it's impossible to debug your problem.

Thank you.

**Comment by DevLKAircrafts** [comment]
Oh, sorry I forgot that...

http://www.mediafire.com/download/ikzk1n20v9qc3a3/A320-200.rar

**Comment by DevLKAircrafts** [comment]
I noticed that this happens everytime I want to make animations with bones.

**Comment by tngreene** [comment]
Has this bug been solved for you yet?

**Comment by tngreene** [comment]
Closed due to lack of activity and the fact that the attached files are now deleted
