### ISSUE TITLE
'Matrix' object has no attribute 'inverted_safe'

### ISSUE THREAD

**Issue by ksgy** [der-On/XPlane2Blender#163]
Hi,

Just updated to v3.3.1 and tried to export an existing blender file and I got the following error:

![untitled-3](https://cloud.githubusercontent.com/assets/683576/13788501/e0023566-ead7-11e5-8be4-e348b3b6db70.png)

**Comment by der-On** [comment]
This seems like a blender bug. The Python API-docs still tell us that `Matrix`-Objects have `inverted_save()` https://www.blender.org/api/blender_python_api_2_77_0/mathutils.html?highlight=matrix#mathutils.Matrix.inverted_safe

As Blender 2.77 is still considered unstable/alpha we should wait until it reaches a stable state.

**Comment by ksgy** [comment]
I'm using blender 2.71, but will try with latest stable (2.76b) - that might be the problem

**Comment by der-On** [comment]
@ksgy Ah that might exactly be the problem. Blender 2.71 might not have this method in the python API.

**Comment by ksgy** [comment]
@der-On Yep, that was the problem, sorry for the false alarm :)

**Comment by der-On** [comment]
no problem.
