### ISSUE TITLE
3.3.4 Release won't enable

### ISSUE THREAD

**Issue by bsupnik** [der-On/XPlane2Blender#164]
When I attempted to do a clean install of the 3.3.4 tag, I got this when I tried to enable the exporter (in the add-ons preferences tab) for the first time:

Read new prefs: /Users/bsupnik/Library/Application Support/Blender/2.76/config/userpref.blend
found bundled python: /Applications/blender-2.76b-OSX_10.6-x86_64/blender.app/Contents/MacOS/../Resources/2.76/python
Traceback (most recent call last):
  File "/Applications/blender-2.76b-OSX_10.6-x86_64/blender.app/Contents/MacOS/../Resources/2.76/scripts/modules/addon_utils.py", line 324, in enable
    mod = __import__(module_name)
TypeError: source code string cannot contain null bytes

This does -not- happen with the 3.3.2 tagged exporter.

STEPS:
1. Do a fresh install of Blender and the add-on, as shown in the new GITHub 3.3 installation instructions notes.
2. For the exporter, download a zip of the tag, copy the io_xplane2blender folder into the addons folder.
3. Start blender, find the xplane exporter and enable it.

**Comment by der-On** [comment]
The __init__.py is in binary format. My new_version.py script was not explicitly saving as text. ;(

**Comment by der-On** [comment]
Fixed now. Release version has not changed.
