### ISSUE TITLE
move "shadow cutoff" setting into materials

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#165]

**Comment by der-On** [comment]
@bsupnik As "Cast shadows" is currently also a global option I'm not sure if we should move this into materials at all. Actually moving shadow settings into materials would mean that the user eventually needs to adjust each material to make it compatible to the reference material.

**Comment by bsupnik** [comment]
Hi Ondrej,

I think this should stay global.  This is applying GLOBAL_no_shadow, right?

Disabling shadow casting isn't really a material property...rather it is 
a one-off hack to exempt entire objects from shadow calculations for 
optimization purposes.

On 3/22/16 10:01 AM, Ondrej Brinkel wrote:
> @bsupnik <https://github.com/bsupnik> As "Cast shadows" is currently
> also a global option I'm not sure if we should move this into materials
> at all. Actually moving shadow settings into materials would mean that
> the user eventually needs to adjust each material to make it compatible
> to the reference material.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/der-On/XPlane2Blender/issues/165#issuecomment-199828416>
>

-- 
X-Plane Developer Blog/SDK: http://developer.x-plane.com/
X-Plane Plugin SDK: http://www.xsquawkbox.net/xpsdk/
Plugin Developer mailing list: x-plane-dev@yahoogroups.com

**Comment by der-On** [comment]
@bsupnik Yes its `GLOBAL_no_shadow`. Closing this now.
