### ISSUE TITLE
..\..\..\..\  symbols after TEXTURE in cockpit_INN.obj

### ISSUE THREAD

**Issue by arb65912** [der-On/XPlane2Blender#171]
Hi Ondrej,

I have never used the "Submit new issue" feature on GitHub, actually I do not even know how to use it by I will try.
Please forgive me my mistakes.

Windows 10   XPlane2Blender version 3.3.4   Blender 2.76

With these    ..\..\..\..\   X-Plane can not read myplane_cockpit maps which are in the main aircraft directory.   I have Relative Path unchecked.  My X-Plane drive is different than where I keep Blender files.

Thank you, cheers, AJ 

[Testplane_cockpit_INN.zip](https://github.com/der-On/XPlane2Blender/files/180560/Testplane_cockpit_INN.zip)

[Testplane.zip](https://github.com/der-On/XPlane2Blender/files/180561/Testplane.zip)

**Comment by der-On** [comment]
Thanks for the report. Will look into it tomorow.

**Comment by arb65912** [comment]
Thank you Ondrej. I hope it os not just something I did wrong and I am not wasting your time.

**Comment by der-On** [comment]
@arb65912 In wich folder exactly are you exporting your object?

I can see that you are using absolute texture paths, which is basically not recommended. The exporter will write the relative path of the texture to the directory you are exporting to.

**Comment by arb65912** [comment]
Hi Ondrej,
I have used relative paths , no difference.

I am on Windows10.

Path to exported file is:
G:\X-Plane 10\Aircraft\Testplane\Testplane_cockpit_INN.obj

Default and night textures paths are:
G:\X-Plane 10\Aircraft\Testplane\Testplane_cockpit.png
G:\X-Plane 10\Aircraft\Testplane\Testplane_cockpit_LIT.png

Sorry for so much trouble but I do not know what to do.

If I skip paths all together and just type in the file names , obj file does not have these //..\..\..\..\ in front of file names.

[Testplane.zip](https://github.com/der-On/XPlane2Blender/files/185189/Testplane.zip)

[Testplane_cockpit_INN.obj.txt](https://github.com/der-On/XPlane2Blender/files/185191/Testplane_cockpit_INN.obj.txt)

**Comment by der-On** [comment]
@arb65912 I currently do not have access to Windows 10, but only Windows 7 and I was not able to reproduce the problem in either of your provided files, with or without relative paths.

I however can see in your second file, that you already have texture paths entered that contain the `../../../` in front of the file name. These will stay on export. Eventually you have moved your blend file after setting the relative file paths? It might be not working because the its not able to find the file on disk using the provided path.

I tried using absolute paths and it worked without any problem.

**Comment by arb65912** [comment]
Hi Ondrej,
I moved the Blender directory and blend files but I think before exporting tests.
What do I do to bring all back?
Should I just reinstall Blender maybe and then setup the exporter?
The addons directory is separated from Blender.

I have Blender Foundation and blender-scripts folders on drive C:
My actual .blend files and X-Plane 10 on different drive G:

Could that be a problem?

**Comment by der-On** [comment]
I think If you just put in the filenames (without absolute paths or `../../../` in front) you should be fine. Reinstalling blender or the addon should not be the problem/solution.

Having Blender and the blend files on seperate partitions is also no problem.

**Comment by arb65912** [comment]
Believe it or not but THAT is exactly what I was doing recently, just nothing in front and my objects found proper maps.

Thank you Ondrej.

Please close that issue.
