### ISSUE TITLE
export

### ISSUE THREAD

**Issue by alexalch** [der-On/XPlane2Blender#174]
"Object will not be exported as it has parent in another layer. Move it parent into layer 1"-What is mean???.(blender 2.77,xplane2blender 3.3.4,)

**Comment by alexalch** [comment]
All objects into layer 1.

**Comment by der-On** [comment]
You have to place parent objects into the same blender-layer as child objects to make child objects export. Blender allows an object to be in multiple layers by shift clicking the layer-boxes in the layer-selection ("m" key).
