### ISSUE TITLE
Animation with single bone exports misoriented object that rotates properly

### ISSUE THREAD

**Issue by arb65912** [der-On/XPlane2Blender#176]
Hi Ondrej,
You must be on vacation as I did not see any input from you.
In this case I hope you are enjoying time of from your hard excellent work. :-)

I have tried to export a single bone elevator half animation probably 500 times by now but with no luck.
I just simply do not know what possibly I might be doing wrong.

I created a video of every step I make and the outcome. 
Notice that bone and object have origins in the same spot.

I really hope that you can figure out what I am doing wrong when you have a chance to look at it.

Thank you.  Cheers, AJ

https://youtu.be/8bt_kGK2dic

I am attaching zipped .bled  and Empanage.obj files.
[Testplane 02 layers added.zip](https://github.com/der-On/XPlane2Blender/files/196825/Testplane.02.layers.added.zip)
[Empanage.zip](https://github.com/der-On/XPlane2Blender/files/196827/Empanage.zip)

**Comment by der-On** [comment]
Static rotations are inverted on the Y-axis. The question is why this happens.

**Comment by der-On** [comment]
@bsupnik The code in charge is here: https://github.com/der-On/XPlane2Blender/blob/v3-3/io_xplane2blender/xplane_types/xplane_bone.py#L388

I'm not sure why we are outputting axis in the following order here: `x, z, y`
but in [_writeEulerRotationKeyframes](https://github.com/der-On/XPlane2Blender/blob/v3-3/io_xplane2blender/xplane_types/xplane_bone.py#L546) we are outputting in order: `z, y, x`

**Comment by arb65912** [comment]
I am sorry for chipping in but it makes me feel a bit better as I have spent two days few hours each and I was thinking I am missing something.
I know you guys will fix it, thank yo so very much.

**Comment by der-On** [comment]
@arb65912 No problem. I will try to create a test case for it, so we can pin down the bug. Thanks for your report.

**Comment by arb65912** [comment]
Thank you VERY much!!!! Can not wait for that fix.

**Comment by arb65912** [comment]
Hi Ben,
Should I retest in the present state?
I am sorry to be such a newbie but did you updated the exporter.
I do not understand what it means " added a commit" ... sorry again to waste your time on these trivial things.
Hi Ondrej, thank you for adding this failing test. I know things will get straightened out.
Thank you both for your constant work on exporter.
AJ

**Comment by der-On** [comment]
@arb65912 We fixed your issue now. Thanks for your report. You've found a fundamental problem we now have been able to resolve!

**Comment by arb65912** [comment]
I am happy I could contribute to find an issue.
There is no new release yet.
Do I just wait or there is any other way to test it?

**Comment by der-On** [comment]
We will soon make a new release after resolving #177
