### ISSUE TITLE
Allow specular intensity greater than 1

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#181]
With the latest version of XP2B, it is not possible to set specular intensity to anything above 1.  I use this feature all the time.  It'd be nice if at least the "custom properties" would overwrite the Blender-imposed limit, but I'm not able to create a custom property that'll overwrite "ATTR_shiny_rat".

**Comment by BlueishGhost** [comment]
I can't even import anything from X-Plane into blender otherwise I would
have half of my http://forums.x-plane.org/index.php?/files/file/32658-kite/
 cockpit done.

Are you going to make a tutorial again Danklaue?  Thanks, if you are!!!!

**Comment by danklaue** [comment]
Not likely I'll be making more tutorials.  I don't think importing is supported, but then again, I haven't kept up-to-date on this project.

**Comment by BlueishGhost** [comment]
okay. sorry I hacked your thread, I was just excited thinking that I could
have a tutorial to go by. How is x-plane going to live without blender I/O?
Is there another program to use?
Thanks, MKTwo

**Comment by danklaue** [comment]
Just use Blender 2.49 with XP2B 3.10. That's what I do. Then open that (or import/append it) in Blender 2.77.

**Comment by BlueishGhost** [comment]
WOW Thanks that's awesome!

Check out my newest aircraft! (God gave me the idea.) It's supposed to be a
bomber that can dogfight.
http://forums.x-plane.org/index.php?/files/file/32658-kite/  Though I
didn't put space for bombs I doubled the dry weight and it still flies
really well. I wish I could get rid of a pitch down attitude that sticks
around till like 540kts or maybe it was 450kts? I don't remember. Anyways
after a certain speed it has a pitch up attitiude. It creeps down, then
after hitting whatever speed it creeps upwards. I finally put on some
artificial stabilizer, but it didn't help.

Anyways, It's good to hear from you again and Have fun on X-Plane.

Mktwo (I used to be Hellion Darklord, but that was too dark for me after a
while.)

**Comment by bsupnik** [comment]
Ondrej & Dan: specular ratios above 1.0 are **totally not supported in X-Plane!!!!!!**

To the extent that they have some effect in X-Plane 10 and the old exporter did export them, the right thing to do (for now) is to support a specular ratio > 1.0.

BUT: a spec ratio above 1.0 absolutely will not be supported in future major versions of X-Plane, and should not be supported in exporters that target them.

**Comment by danklaue** [comment]
Then we need SOMETHING to make glass look less like plexiglass, or spinners or fuselage objects to have this soft, fuzzy look to them. We need more control over things like specular colour (via specular maps), specular size, specular hardness.  Not having that kind of control really sucks.  

The border of the specular set to 1 in X-Plane is so soft and fuzzy, it makes hard stuff like glass and metal and fibreglass or carbon fibre look totally soft, almost spongy.

**Comment by der-On** [comment]
@bsupnik do you have any suggestions on how these kind of effects can be achieved in future?

**Comment by bsupnik** [comment]
I think the long term answer is a better material model in X-Plane, at 
which point values outside of the material model's defined parameter 
ranges will hopefully not be necessary.

**Comment by danklaue** [comment]
Fine, we can close this, as exaggerated specular values are no longer supported in v11 anyway.
