### ISSUE TITLE
Allow defining textures set in export settings to override textures assigned to materials for backward compatibility.

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#182]
All of my older projects don't have materials configured with textures.  I always relied on the export process to link up the correct texture to my object.  This allowed me to have .psd files or LIT textures linked to my Blender visualization, but when I export it, I expect it to take the textures I assigned in the exporter window.  This should not change, as it is a lot of work to go back and assign a texture to every material.  Should not be necessary to require a texture be attached to the material, as in X-plane, you have one texture per object anyway.

The feature to detect textures automatically is good... but for backward compatibility, it should be a matter of un-ticking that feature, and it should be filled out with the textures set by previous versions of the project, overriding the requirement to have a texture assigned to the material.

**Comment by bsupnik** [comment]
Ondrej - this sounds like a simple regression bug? I think having the texture overrides "just work" for legacy projects was the intended behavior from day 1.

Dan, can you provide a simple one-object .blend + texture file that demonstrates this (e.g. has one texture for materials, a different "override" path, and exports the -wrong- texture)?  Again, we'll use the .blend file in our test suite.

**Comment by danklaue** [comment]
[RV-9_LegacyExport.zip](https://github.com/der-On/XPlane2Blender/files/264790/RV-9_LegacyExport.zip)


OK, after some tests, I've figured out exactly what's going on.  The above attached file contains a simple cube, which has been exported using Blender 2.72 and XP2B 3.20.  Basically, the new version (3.3.10) should simply NOT have the "Autodetect Textures" check box checked by default.  That way, it'll take over the textures that were assigned to the object in XP2B 3.20.

Exporting the RV-9_Test.blend file using XP2B 3.20 results in an .obj file that has correctly assigned textures.  This is how all my planes are set up.

Opening that same project using XP2B 3.3.10 will break the file paths of the example file above, because the "Autodetect Textures" option is selected, but there are no textures to auto detect, since they were not defined in the material.  In this case, the checkbox should remain turned off, so that it can use the same textures that were assigned to that object by XP2B 3.20. 

I noticed that you can turn off the checkbox manually, and it'll fill in the texture info for 3.20, provided you haven't already saved the .blend file before having un-checked the check box.  If you save the .blend file before un-checking that box, it'll put blanks in for the texture paths, and the originals are unrecoverable.



![b2 77_xp2b3 3 10_ad_on_blank_textures](https://cloud.githubusercontent.com/assets/359923/15271627/6e6d89b2-1a18-11e6-971a-b07965633e56.jpg)
![exportedwithxp2b3 3 10](https://cloud.githubusercontent.com/assets/359923/15271628/6e86fe24-1a18-11e6-871b-86bb550e2a03.jpg)


![b2 77_xp2b3 3 10_ad_off](https://cloud.githubusercontent.com/assets/359923/15271633/7b6b43c0-1a18-11e6-93c5-1a24ec77c8d0.jpg)
![exportedwithxp2b320](https://cloud.githubusercontent.com/assets/359923/15271632/7b6982c4-1a18-11e6-874f-20000ce839c0.jpg)


![b2 77_xp2b3 3 10_ad_off](https://cloud.githubusercontent.com/assets/359923/15271634/81b030ce-1a18-11e6-89e0-cb1beb472b3c.jpg)

**Comment by bsupnik** [comment]
Ondrej - I'd like to know our options here in terms of how new plugin-specific data is created. I agree that ideally a legacy 3.20 project should open with the overrides on to match 3.20.  

But I really don't want a brand new 3.30 project to be born with these settings, because the work-flow we should encourage going forward (e.g. the one that is easier for authors and less astonishing) is WYSIWYG.

**Comment by danklaue** [comment]
I think it's a simple matter of sensing whether the project is a  "legacy" project. I.e., if the blanks for textures are already filled out, due to it coming from a previous version, the check-box to auto-detect textures should be OFF, and the texture slots should be filled in with those coming from the legacy project.

**Comment by der-On** [comment]
The updater is responsible for these kind of things. I just need to add this behaviour if it finds something older v3.3.

**Comment by der-On** [comment]
Fixed it now. Updater had this code already but a later change did not made it work.
