### ISSUE TITLE
Armature animation is not required

### ISSUE THREAD

**Issue by cpuwolf** [der-On/XPlane2Blender#185]
Bender can bake object animation from Armature. so I think you should not take too much time on bones animation

**Comment by arb65912** [comment]
Hi, could you explain it in more details?

**Comment by cpuwolf** [comment]
At present, Xplane only supports rigid object animation, meaning vertex animation is not supported.
usually you parent rigid object to a bone, then use bone to animate. after animation is done, you can use Blender "Bake Animation" to create location&rotation keyframes on the rigid object, at this time, you can totally removed the bones, and your rigid animation is there

**Comment by cpuwolf** [comment]
I mean even if your addon support bone animation, we still are able to temperaily use bone to create beautiful animation, then remove bones, then bake animation, then export

**Comment by airfightergr** [comment]
Vertex animation is in X-Plane's future list. @bsupnik will have more info about that.

**Comment by bsupnik** [comment]
The next -major- revision of the OBJ file format will support bone hierarchy animations with multiple bones (with weights) on a per-vertex basis.

I also don't understand what the "todo" or "bug" or "feature request" is in this bug. The intention of the Blender 2.7 exporter is to support two forms of animation:
- Loc/rot keyframes on data blocks nad
- Bones/armatures.

Bones/armatures are needed to support bringing 2.49 Blender files forward.
Loc/rot animations are required to support projects made with the previous version of this exporter.

So both are mandatory for the exporter - authors can use whichever they want. Both are expected to be WYSIWYG.

**Comment by cpuwolf** [comment]
yes you are right. bake animation is not "smart" enough
