### ISSUE TITLE
Objects not exported when they don't have a material

### ISSUE THREAD

**Issue by JasonGilholme** [der-On/XPlane2Blender#191]
I'm not sure why they wouldn't go out.  Even when you have "Autodetect textures" on, it should just skip any texture gathering and write the mesh.

Blender 2.77 with xp2b 3.3.11

**Comment by der-On** [comment]
@JasonGilholme v3.3 does some sanity checks to only output valid objects and materials that will look predictable in X-Plane. An object with no material will most likely lead to unpredictable results.

**Comment by tngreene** [comment]
Closed due to it being a bad idea. @der-On is right, an object with no material will mostly likely lead to unpredictable results. In addition, it is easy enough to just hit New Material for quick testing.
