### ISSUE TITLE
no material found 

### ISSUE THREAD

**Issue by mike44** [der-On/XPlane2Blender#192]
Inadvertently saved a 2.49 in 2.67 and now I can't export. It doesn't find any material. I have tried in vain everything possible.
[test.blend.zip](https://github.com/der-On/XPlane2Blender/files/301999/test.blend.zip)
Thanks for a fix.

**Comment by der-On** [comment]
@mike44 Could you please explain, why you closed this issue? Have you found a workaround or something? Thx

**Comment by mike44** [comment]
I have not had that problem for a while. So maybe it was just a random error caused by something rare. 
I can reopen if you prefer, but look forward foremost for a fix to bug 196.
