### ISSUE TITLE
datarefs missing

### ISSUE THREAD

**Issue by mike44** [der-On/XPlane2Blender#194]
It exports fine both datarefs with 3.2 but with 3.3 only one dataref.
[datarefbug.blend.zip](https://github.com/der-On/XPlane2Blender/files/310159/datarefbug.blend.zip)

**Comment by JasonGilholme** [comment]
How good are you with code?  I have a fix for this.  I can commit something for you if you're able to pull it down and use it.

**Comment by BlueishGhost** [comment]
Can there be a list of error troubleshooting for animations? Like a message
outlining what to do?

**Comment by JasonGilholme** [comment]
@BlueishGhost if you have feature requests, you should make your own issue so the owner of the project can see them clearly.  Chances are he won't see them in here or they will get lost.

**Comment by BlueishGhost** [comment]
How do i do that?

**Comment by JasonGilholme** [comment]
https://guides.github.com/

**Comment by mike44** [comment]
HiI haven't used git for a while. I need to create a fork before the pull. Anyway where's der-on? Now with 10.5 I want to try the latest scroll wheels etc.Thanks

**Comment by JasonGilholme** [comment]
I might make my own fork of this project anyway. I'm a pipeline TD for a visual fx company by day so the whole import export thing is right up my alley.  There are a few things i'd like to add, even if they're just for myself.

I'll try to do this over the next few days at some stage.  It will have fixes for the couple of issues I've reported over the last week or so.

Not sure where der-On is.  Probably just caught up with the real world.  It happens.

**Comment by bsupnik** [comment]
Hi Y'all,

Ondrej works on this exporter as a hobbyist and as a contractor and in 
the later capacity he sometimes has limited availability.

If you guys want to be able to create useful branches and keep them 
working with the project in the long term, I would suggest the following:

1. Discuss proposed new features with me (ben at x-plane dot com) to 
find out if they can make it back to trunk and/or will conflict with 
other proposed development and

2. Consider keeping features in their own topic branches (and then 
'merge together' your topics to produce your custom build) - that way we 
can pull in topic branches on a per-feature basis and not be stuck with 
"oh no, we have to take everything to get anything."

Generally speaking, both Ondrej and I think it would be fantastic if the 
community gets involved in the tool chain.  Jason, based on your day job 
you may be in a unique position to really understand what the exporter 
is supposed to do.

cheers
Ben

**Comment by mike44** [comment]
@BlueishGhost you can simply download the zip
@JasonGilholme do you have some fixes now?
I'm almost to the point waiting for fixes to continue, but never used python before to fix myself.

**Comment by bsupnik** [comment]
@JasonGilholme  Do you have a pull request for a fix for this?

**Comment by JasonGilholme** [comment]
@bsupnik I haven't been in this code for a while.  I think I'm due for a change in scenery.  It's just a formality but I'll get a pull req sorted over the weekend.

**Comment by JasonGilholme** [comment]
@bsupnik I've submit pull requests for the useful things I have locally.

@mike44 If you want to try it out sooner, it's here:  https://github.com/JasonGilholme/XPlane2Blender/tree/%23194-datarefs_missing

**Comment by mike44** [comment]
Great work. Many thanks
