### ISSUE TITLE
material errors

### ISSUE THREAD

**Issue by mike44** [der-On/XPlane2Blender#195]
In 3.3 I get tons of:

ERROR: Material "noshadow" in object "Tri.117" Must not be part of the cockpit panel.
ERROR: Material "noshadow" in object "Tri.117" Must not be a manipulator.

but it must be a manipulator and works fine in 3.2
Thanks

**Comment by der-On** [comment]
@mike44 Please attach a file so we can reproduce this.

**Comment by mike44** [comment]
Sorry my fault, closed. I have a look at scroll wheel now and still miss most datarefs as in my other bugreport 194.Great to see you back Ondrej.

**Comment by mike44** [comment]
PS: scroll wheel doesn't work in 10.5? No luck so far.

**Comment by airfightergr** [comment]
@mike44 weird... it works even on 10.45!
