### ISSUE TITLE
Wrong export of show/hide animations

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#196]
In version 3.2 of the exporter, it was possible to have something like shown in the picture. 

![unbenannt jpg 09d3b125c639003bfb1b03c7b57206a6](https://cloud.githubusercontent.com/assets/359399/16874128/e2186026-4a97-11e6-86df-979d86f3b7e3.JPG)

 The object would then only be visible, if the dataref was 3. Now this doesnt seem to be possible anymore.

It is now exported like:

```
TRIS    61626 1788
    ANIM_begin
    ANIM_hide    0    1    sim/cockpit2/switches/custom_slider_on[15]
    ANIM_end
    ANIM_begin
    ANIM_hide    0    3    sim/cockpit2/switches/custom_slider_on[15]
    ANIM_end
    ANIM_begin
    ANIM_hide    0    2    sim/cockpit2/switches/custom_slider_on[15]
    ANIM_end
    ANIM_begin
    ANIM_hide    0    0    sim/cockpit2/switches/custom_slider_on[15]
    ANIM_end
    ANIM_begin
    ANIM_hide    1    99    sim/cockpit2/switches/custom_slider_on[15]
    ANIM_end
```

Before it was:

```
    ANIM_begin
        ANIM_hide    0.00000000    2.00000000    sim/cockpit2/switches/custom_slider_on[15]
        ANIM_hide    4.00000000    99.00000000    sim/cockpit2/switches/custom_slider_on[15]
        ATTR_no_cockpit
        ATTR_cockpit
        TRIS    68889 6 
```

**Comment by mike44** [comment]
Yes, same in the attached *.blend. Many thanks for fixing.
[bug2.blend.zip](https://github.com/der-On/XPlane2Blender/files/367143/bug2.blend.zip)
