### ISSUE TITLE
xplane export log 

### ISSUE THREAD

**Issue by brisnel** [der-On/XPlane2Blender#198]
hey I have a problem exporting objects and every time I try nothing shows up in my airplane objects file and I get this error 
export log produced an error or warning 
Please take a look into the internal text file xplane2blender.log

**Comment by airfightergr** [comment]
http://forums.x-plane.org/index.php?/forums/topic/94117-xplane2blender-v33/&do=findComment&comment=1002494

**Comment by brisnel** [comment]
i don't get i looked every where i can't find this[attachment=213586:blend.jpg]

**Comment by airfightergr** [comment]
![blender](https://cloud.githubusercontent.com/assets/16308752/17652210/3cb1dfc2-627f-11e6-803d-d35dcb3c9f7e.png)

**Comment by brisnel** [comment]
sorry but my computer can't seem to find xplane2blender.log

**Comment by brisnel** [comment]
ok I have found it so know i change it to blend.jpg

**Comment by der-On** [comment]
This needs a mention in the docs.
