### ISSUE TITLE
Material diffuse color (ATTR_diffuse_rgb) not exported

### ISSUE THREAD

**Issue by JDeeth** [der-On/XPlane2Blender#201]
The material diffuse color and intensity is not being exported as of Blender 2.78 and XP2B 3.3.10.

To reproduce:
Install Blender and XPlane2Blender as per the docs, including setting up an empty starting scene
Add X-Plane Layers from properties>scene
Name layer 1 as "redcube"
Add a cube
Add a material to the cube
Set the material's diffuse RGB to 255,0,0
Export the layer as an X-Plane object
Open redcube.obj in a text editor and note the lack of any ATTR_diffuse_rgb line

Attached: the .blend and .obj files
[ATTR_diffuse_rgb not exported.zip](https://github.com/der-On/XPlane2Blender/files/517805/ATTR_diffuse_rgb.not.exported.zip)

**Comment by der-On** [comment]
@JDeeth `ATTR_diffuse_rgb` is deprecated and thus will not be exported. Please use texture images to set material colors.

**Comment by JDeeth** [comment]
Thanks - I'll try to be less archaic in my modelling :)
