### ISSUE TITLE
can't export my cockpit obj on blender 2.77

### ISSUE THREAD

**Issue by brisnel** [der-On/XPlane2Blender#202]
I can't seem to export my cockpit obj check the pic and tell me if i am doing spmething wrong
<img width="1439" alt="capture d ecran 2016-11-08 a 17 27 55" src="https://cloud.githubusercontent.com/assets/21010886/20119103/90c33da8-a5dd-11e6-85b7-623c1933758a.png">
<img width="843" alt="u" src="https://cloud.githubusercontent.com/assets/21010886/20119107/94b7b3d0-a5dd-11e6-8c98-52702507e399.png">

**Comment by der-On** [comment]
To be able to debug this, I would need the file containing the cockpit. Do you have any output in the internal text file xplane2blender.log?

**Comment by brisnel** [comment]
<img width="730" alt="capture d ecran 2016-11-12 a 21 32 16" src="https://cloud.githubusercontent.com/assets/21010886/20243119/95553a02-a91f-11e6-927d-64f5f00506a1.png">

**Comment by der-On** [comment]
I think if you follow the messages and correct the material settings your export will work.

**Comment by brisnel** [comment]
ok i have correct everything and now it exports but in x-plane i don't see any animated texture just a panel

**Comment by brisnel** [comment]
and i don't get any error

**Comment by airfightergr** [comment]
Have you assigned in the materials tab that is a part of cockpit panel?

**Comment by brisnel** [comment]
no
