### ISSUE TITLE
Specular intensity controls no longer present in latest update

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#203]
Unless I'm missing something, release 3.3.11 (May 24) does not permit setting specularity anymore, despite the fact that the manual states it's possible.

Manual:
<img width="675" alt="screen shot 2016-11-11 at 10 42 41 pm" src="https://cloud.githubusercontent.com/assets/359923/20235736/3618b7b8-a860-11e6-93c9-fd4c048c806f.png">

v3.3.11:
<img width="712" alt="screen shot 2016-11-11 at 10 40 54 pm" src="https://cloud.githubusercontent.com/assets/359923/20235737/48478a9a-a860-11e6-8685-2277dde1fdda.png">

**Comment by der-On** [comment]
Specular intensity is still taken from Blenders material specularity which only allows values from 0 .. 1.
Overriding the intensity to values > 1 is considered deprecated and a hack that will no longer work in future X-Plane versions. To achieve the glossy effect reflections should be used instead.
