### ISSUE TITLE
Bone Animation export problem

### ISSUE THREAD

**Issue by JorikMi** [der-On/XPlane2Blender#204]
Hi guys,

I'm still learning how to model and animate in Blender but for the moment I'm stuck at animating a windsock.
I use a bone animation to animate the rotation depending on the wind direction using dataref "Sim/graphics/animation/windsock psi" using the values 0, 90, 180, 270 and 360 for the wind direction.
I use a timeline from 1 to 361 frames and add a keyframe "LocRot" on 1, 91, 181, 271 and 361 and linking them using the Bone xplane2blender properties.
But when exporting this animation the .obj file animation part isn't exporting correctly.
![xplaneboneanimation](https://cloud.githubusercontent.com/assets/23658571/20526391/23c2a4c2-b0c4-11e6-8bb7-101149bba384.JPG)

This is what I get in the .obj file:
ANIM_begin
	ANIM_trans	0	6	0	0	6	0
	ANIM_rotate	1	0	0	0.00000068	0.00000068
		ATTR_shiny_rat	0
		TRIS	0 1152
	ANIM_end
The dataref isn't even mentioned.

Could you guys help me out on this problem?

Thanks in advance.
And thanks to the developers of this addon for blender giving us a free magic box for creating content for xplane!

Cheers
Jorik

**Comment by JorikMi** [comment]
[LLHwindsockWithoutpole.zip](https://github.com/der-On/XPlane2Blender/files/607497/LLHwindsockWithoutpole.zip)
Here is the .blend file I'm talking about.

cheers 
jorik

**Comment by andertal** [comment]
It is not a BUG, but a misuse.
Keyframe on a bone must not be placed in "Object Mode" but in "Pose Mode"...
And then it works

andertal

**Comment by andertal** [comment]
this is what i get in the .obj file:
# 0 ROOT
# 1 Object: Armature
# ARMATURE: Armature	weight: 0
	# 2 Bone: Bone
	ANIM_begin
	# static translation
	ANIM_trans	0	6	0	0	6	0
	# static rotation
	ANIM_rotate	1	0	0	0	0
	# rotation keyframes
	ANIM_rotate_begin	0	1	0	sim/graphics/animation/windsock_psi
	ANIM_rotate_key	0	0
	ANIM_rotate_key	90	90
	ANIM_rotate_key	180	180
	ANIM_rotate_key	270	270
	ANIM_rotate_key	360	360
	ANIM_rotate_end
		# 3 Object: Mesh
		# PRIMITIVE: Mesh	weight: 0
		# MATERIAL: Material
		ATTR_shiny_rat	0
		TRIS	0 1152
	ANIM_end

# Build with Blender 2.76 (sub 0) (build b'48f7dd6') Exported with XPlane2Blender 3.3.12

the .blend modified:
[LLHwindsockWithoutpole.zip](https://github.com/der-On/XPlane2Blender/files/625362/LLHwindsockWithoutpole.zip)

**Comment by der-On** [comment]
So this can be closed?

**Comment by JorikMi** [comment]
Hi guys,

Sorry for my late response but I'm very busy at work.
When I export the blend file you send me I get this in my object file.
# 0 ROOT
# 1 Object: Armature
# ARMATURE: Armature	weight: 0
	# 2 Bone: Bone
	ANIM_begin
	# static translation
	ANIM_trans	0	6	0	0	6	0
	# static rotation
	ANIM_rotate	1	0	0	0.00000068	0.00000068
	# rotation keyframes
	ANIM_rotate_begin	0	1	0	sim/graphics/animation/windsock_psi
	ANIM_rotate_key	0	0
	ANIM_rotate_key	90	89.99999567
	ANIM_rotate_key	180	179.99999135
	ANIM_rotate_key	270	270.00000068
	ANIM_rotate_key	360	360.00001002
	ANIM_rotate_end
	ANIM_rotate_begin	0	0	-1	sim/graphics/animation/windsock_psi
	ANIM_rotate_key	0	0
	ANIM_rotate_key	90	0.00000068
	ANIM_rotate_key	180	0
	ANIM_rotate_key	270	-0.00000068
	ANIM_rotate_key	360	0
	ANIM_rotate_end
	ANIM_rotate_begin	1	0	0	sim/graphics/animation/windsock_psi
	ANIM_rotate_key	0	0
	ANIM_rotate_key	90	0.00000068
	ANIM_rotate_key	180	0.00000137
	ANIM_rotate_key	270	0.00000068
	ANIM_rotate_key	360	0
	ANIM_rotate_end
		# 3 Object: Mesh
		# PRIMITIVE: Mesh	weight: 0
		# MATERIAL: Material
		ATTR_shiny_rat	0
		TRIS	0 1152
	ANIM_end
So it repeats 3 times.
![xplaneboneanimation](https://cloud.githubusercontent.com/assets/23658571/20882346/c30b0e04-bae0-11e6-981b-1e3269cad5e2.JPG)
If I try the keyframing in Pose mode and export I get this in the object file
ANIM_begin
	ANIM_trans	0	6	0	0	6	0
	ANIM_rotate	0	1	0	-180.00000501	-180.00000501
	ANIM_rotate	0	0	-1	0.00000043	0.00000043
	ANIM_rotate	1	0	0	0	0
	ANIM_rotate_begin	0	1	0	Sim/graphics/animation/windsock psi
	ANIM_rotate_key	0	0
	ANIM_rotate_key	270	90.0000025
	ANIM_rotate_key	180	180.00000501
	ANIM_rotate_key	90	270.00000068
	ANIM_rotate_key	360	360.00001002
	ANIM_rotate_end
		ATTR_shiny_rat	0
		TRIS	0 1152
	ANIM_end

The first part seems not right.

**Comment by tngreene** [comment]
Closed due to lack of activity and because people got it right: You need to keyframe in pose mode
