### ISSUE TITLE
Can't compile normal texture and I dont know why...

### ISSUE THREAD

**Issue by remipfr** [der-On/XPlane2Blender#205]
Hi ! I can't compile both normal/secular map in a new work and I don't understand why. 

![capture d ecran 1](https://cloud.githubusercontent.com/assets/24356770/21753153/cbda9ab0-d5e6-11e6-8402-8fe2d9dd4a6a.jpg)

Please help !

**Comment by der-On** [comment]
Looks like a compatibility problem with newer blender versions. Seems like we cannot create RGBA images anymore, like we did before.

**Comment by remipfr** [comment]
Thanks for reply, finally I succeed to export the compiled textures with an other blend file that work. And I select manually my texture in the right file after.

**Comment by remipfr** [comment]
http://xplane.anzui.de/ dosen't work ?

**Comment by der-On** [comment]
The site is and will stay down. Yes.

**Comment by remipfr** [comment]
Why ? It was a very nice tool.

**Comment by der-On** [comment]
If you mean the dataref search. This will most propably come back in another fashion. But I can't tell when. If you mean the flight planner, it's new version is online here: https://der-on.github.io/X-Plane-Flight-Planner/

**Comment by remipfr** [comment]
Lookq very nice ! Thx !

**Comment by tngreene** [comment]
@remipfr can you attach the blender file you were wroking on there?

**Comment by remipfr** [comment]
Hi, here is the file that succeed to compile the normal and specular textures.

[Wing L.blend.zip](https://github.com/der-On/XPlane2Blender/files/832200/Wing.L.blend.zip)

**Comment by tngreene** [comment]
Sweet, thank you so much. Do you also have the file that wasn't working anymore? In addition, what version of Blender were you using? 2.77? 2.78? You can tell by looking at the splash screen (Help->Splash Screen if you've disabled it)

**Comment by tngreene** [comment]
test_composite.test has passed successfully. I don't know if that means this bug is closed, since we don't have the original problem file. It could be a coincidence.

**Comment by remipfr** [comment]
You're welcome of course. I use Blender 2.77 with xplane2blender 3.3.12 on mac OS 12. Here is the file who don't compile both textures.
[Wing L.blend.zip](https://github.com/der-On/XPlane2Blender/files/834974/Wing.L.blend.zip)

**Comment by tngreene** [comment]
I'm going to mark this as closed. No feedback for a month on it and it passed the test? Sounds good for me.
