### ISSUE TITLE
Keyframes not exported when when keyed values match

### ISSUE THREAD

**Issue by kucoman** [der-On/XPlane2Blender#206]
Using Blender 2.78a + XPlane2Blender-3.3.10
When exporting a bone animation where consecutive frames have the same value (eg: Loc animation where X, Y, Z don't change), the second frame is not exported. The problem is solved if the values are changed. I understand this is not the expected behavior, as it might be problematic for some animations. I have experienced this in a file exporting fine in the previous  3.20.

Here the case where the frames are missing:
	ANIM_begin
	ANIM_trans	0.12405	0.90618193	2.65460658	0.12405	0.90618193	2.65460658
	ANIM_rotate	0	0	-1	89.99994786	89.99994786
	ANIM_rotate	1	0	0	90.0000025	90.0000025
	ANIM_trans_begin	Dataref/here
	**ANIM_trans_key	0	0	0	0
	ANIM_trans_key	0.17471157	0	0	0.011
	ANIM_trans_key	0.30000001	0	0	0**
	ANIM_trans_end			
	ANIM_end

Here the complete animation modifying position values a small amount:
	ANIM_begin
	ANIM_trans	0.12405	0.90618187	2.65460658	0.12405	0.90618187	2.65460658
	ANIM_rotate	1	0	0	90.0000025	90.0000025
	ANIM_trans_begin	Dataref/here
	ANIM_trans_key	0	0	0	0
	ANIM_trans_key	0.14368001	**-0.001**	0	0
	ANIM_trans_key	0.174712	-0.011	0	0
	ANIM_trans_key	0.253784	**-0.0111**	0	0
	ANIM_trans_key	0.30000001	**-0.001**	0	0
	ANIM_trans_key	1	0	0	0
	ANIM_trans_end
	ANIM_end 

I hope that helps. Very good work.
Let me know if I can clarify anything.

**Comment by kucoman** [comment]
I just realized the two cases where not consecutive. There is a change in the axis animation. This is because I redid the animations several times until I realized what was going on. Apart of that, I think the example shows the point.

**Comment by dpospisil** [comment]
I am seing this issue also on non-armature object type animations.

**Comment by bsupnik** [comment]
This may be related to issue #215

**Comment by kucoman** [comment]
Certainly.

**Comment by tngreene** [comment]
See #215 and for the fix15a157bd9e88e
