### ISSUE TITLE
Manipulator's cursor "down" is duplicated, and "up-down" is missing

### ISSUE THREAD

**Issue by kucoman** [der-On/XPlane2Blender#207]
Using Blender 2.78a + XPlane2Blender-3.3.10, under Linux.
In Blender, go to object's tab. In the section Manipulator, the drop-down list for cursor does not list "up-down" item, and "down" is duplicated.

Cheers!

**Comment by der-On** [comment]
This got fixed in 3.3.12

**Comment by kucoman** [comment]
Is this version already public?

Untitled Document

Ivan Arroyo González
Arquitectura, Artes Visuales, Artes Plásticas
www.ivanarroyo.es <http://www.ivanarroyo.es>
kucoman@gmail.com <mailto:%20kucoman@gmail.com>
+34649799803

**Comment by der-On** [comment]
Migth have missed to write about itin the forums, but you get all releases here: https://github.com/der-On/XPlane2Blender/releases

**Comment by kucoman** [comment]
Thanks for the pointer.
