### ISSUE TITLE
Error while exporting

### ISSUE THREAD

**Issue by welljsjs** [der-On/XPlane2Blender#208]
Hello, 

I just downloaded the 2.78a Blender and the 3.2Xplane2Blender. I followed the steps in the documentation for "installing".
But if I am trying to export any file, it always gives me an error:

##### _location:_ -1
<br><br>

Maybe it is also my mistake, hope you can help me soon. 

Thanks in advance!

**Comment by bsupnik** [comment]
Hi,

Please attach a small .blend file that reproduces this bug.

**Comment by welljsjs** [comment]
Hey, 
well, I could solve my problem some time ago, so the error does not occur anymore. If you want, I can try to reproduce the error, but it will take some time because I don't exactly know what I changed until now.
