### ISSUE TITLE
Can't check the box in user preferences/addons

### ISSUE THREAD

**Issue by Sloboda76400** [der-On/XPlane2Blender#213]
Hello,
i have download Blender 2.6 and unrip 3.3.10 in addons,
Blender see it in import/export addons, but i can't check the box.
Could you help me please ?
Thanks,
Guillaume

**Comment by CanaryRob** [comment]
Same.

**Comment by tngreene** [comment]
Can you try again with Blender 2.77 or do you need 2.6?

**Comment by tngreene** [comment]
I can confirm, Blender 2.72 or higher is needed to use XPlane2Blender. I recommend using 2.77 or higher.

Is there a particular reason you use 2.6? Which version of it? I realize this bug was filed on Feb 27th. What is your current set up (and sorry for the delay).

**Comment by tngreene** [comment]
Closed due to lack of activity or repeatably. If you have more issues please feel free to make another bug with more details
