### ISSUE TITLE
Multi Root object export error

### ISSUE THREAD

**Issue by alxunru** [der-On/XPlane2Blender#214]
When running root export for multiple OBJs within the same scene, all of the EMPTY containers (and the data that they are hauling around), are displaced from where they are in the scene to the origin (0,0,0) in the 3D space. Once the export is complete, instead of putting these EMPTYs back to where they were originally, everything remains at 0,0,0. This is fine for airplanes where all EMPTYs should be at 0,0,0 anyway, but for scenery objects, it's definitely an issue. The EMPTYs shouldn't be moved by the exporter.

Additional (beyond what I've sent) example files are available by request

**Comment by bsupnik** [comment]
@alxunru  I just want to confirm that "as of now", this bug is "fixed" in that the empties do NOT move to the origin but #263 still exists - the origin of the written OBJs is wrong.

**Comment by alxunru** [comment]
I can confirm that the empties DO NOT move to the origin, but that the origin of the written objects is wrong. All objects export as if 0,0,0 in Blender was the origin, not the individual empties.

**Comment by bsupnik** [comment]
cca8c76cb6635bc42c854d801f9e631edfe31512
