### ISSUE TITLE
Duplicate Key Frame Lost

### ISSUE THREAD

**Issue by bsupnik** [der-On/XPlane2Blender#215]
In the example Blender file, the animation features three key frames at 0, 0.8 and 1.0.  The translation at 0.8 and 1.0 is the same, so that X-Plane will stop moving the cube from all times between 0.8 and 1.0 inclusive.  (With only 0 and 0.8, X-plane will extrapolate linear movement at t > 0.8 based on the 0 and 0.8 key frames).

The exporter does not export key frame data for time 1.0 for some reason.  This is a regression bug;older versions of the exporter do not do this.

EXPECTED OUTPUT (animation only)
ANIM_begin
ANIM_trans_begin	sim/cockpit2/controls/flap_ratio[0]
ANIM_trans_key	0	0	0	-3.39706278
ANIM_trans_key	0.80000001	0	0	-1.69328952
ANIM_trans_key	1.0	0	0	-1.69328952
ANIM_trans_end

ACTUAL OUTPUT (animation only)
ANIM_begin
ANIM_trans_begin	sim/cockpit2/controls/flap_ratio[0]
ANIM_trans_key	0	0	0	-3.39706278
ANIM_trans_key	0.80000001	0	0	-1.69328952
ANIM_trans_end

**Comment by bsupnik** [comment]
[QueboidLocationRatioFlapThingy.blend.zip](https://github.com/der-On/XPlane2Blender/files/811754/QueboidLocationRatioFlapThingy.blend.zip)

**Comment by bsupnik** [comment]
Source blender file zipped and attached.

**Comment by tngreene** [comment]
Can confirm this also happens on Blender 2.77

**Comment by tngreene** [comment]
I bisected and checked out commits as far back as 2 years ago (8/7/2015) but could not find a past version which did not produce an incorrect OBJ. @bsupnik do you know which version this did not happen in?

**Comment by tngreene** [comment]
Fixed in commit 15a157bd9e88e. The problem was a premature optimization in xplane_bone. It was checking if there were two duplicate frames in a row, and dropping the second, even if it was a valid part of the transformation.
