### ISSUE TITLE
Objects parented to empties and animated, sometimes generate large locational offsets.

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#219]
In this example, I have a simple set of knobs that are animated around their rotational axes, and are parented to an empty. 

(The empty allows for easy alignment to slanted instrument panels, bypassing the use of bones, which are more cumbersome to use in complex scenes, as they have a pose mode, which precludes them from selection in certain cases.)

In v3.20 of the exporter, the knob is exported correctly, its position is correct, and its rotational axis passes right through the centre of the knob, and is aligned to the rotation of its parent empty (and with that, the rotation is perpendicular to the slanted panel, as it should be.)

When exporting that very same scene in v3.30, the knob's mesh goes off into 3D space that seems to coincide with that knob's distance from the centre of the scene.  (I.e., if the knob is located 3.2 meters in front of the centre of the scene, the offset of that knob seems to be another 3.2 metres forward.)

The axis of the rotation animation of that knob also is affected, and the knob no longer rotates around its own geometry. 

This problem does not seem to be in play 100% of the time, but I cannot figure out what the variable is with other knobs that seem to be set up identically, but behave correctly after export using v3.3.

[v3.2_v3.3_discrepancy_parenting_knobs_to_empties.zip](https://github.com/der-On/XPlane2Blender/files/825761/v3.2_v3.3_discrepancy_parenting_knobs_to_empties.zip)

**Comment by tngreene** [comment]
Hi @danklaue, I've been working on trying to replicate this bug and track it down. Your bugs are not getting ignored, believe me. I've made a small test case and uploaded it, and the results from running the exporter from the commit e046b255b87201480bfcbd099 (just after the release of 3.20.14, when all the files were moved into a more convenient folder) to the most recent commit (6fa70244c661).

Can you tell me if this file replicates the problem and is indeed a simpler version of the file you've uploaded? I'm having a little trouble understanding whats going on myself.

**Comment by tngreene** [comment]
[219_simple_case.zip](https://github.com/der-On/XPlane2Blender/files/953509/219_simple_case.zip)

**Comment by danklaue** [comment]
It does NOT reflect the problem.  I think the actual problem is based on this issue:
https://github.com/der-On/XPlane2Blender/issues/241

If I take your very example files, no matter if rotation or no rotation, and add a second dataref to the cube (in my case, com1), the problem occurs.  So: the parenting or non-parenting to an empty does NOT seem to be the defining variable... the variable is twofold: 

-assigning more than one dataref to the animation
-using the "ROT" directive, as opposed to the "LocRot" directive

as per the attached examples:

[219_simple_case_no_rotation.zip](https://github.com/der-On/XPlane2Blender/files/955671/219_simple_case_no_rotation.zip)
[219_simple_case_with_rotation.zip](https://github.com/der-On/XPlane2Blender/files/955672/219_simple_case_with_rotation.zip)

Now, I can't exactly make sense of what's happening here.  But what it seems like to me is:

-3.20 exports this properly.
-3.30 makes a distinction between the parts that are parented to an empty (no matter if rotated or not), and those that aren't parented to an empty.  
-3.30 seems to make a distinction between whether "LocRot" or "Rot" is used.  

That's all I have time for right now.

**Comment by danklaue** [comment]
Still a problem.  I'll try to author some more test cases.
