### ISSUE TITLE
Xp-11 specific features?

### ISSUE THREAD

**Issue by JasonGilholme** [der-On/XPlane2Blender#221]
Hi,

This is more of a question at the moment, but I imagine it could result in tickets / issues.

What xp11 renderer specific attrs can / should be exposed to artists to best leverage the new technology available?  There's been a considerable overhaul of the renderer and I imagine there would be some changes necessary to the artists tool set to go along with this.

@bsupnik what viewport features does blender provide that you think we could leverage to get an accurate representation of the xp11 renderer?

Jason

**Comment by tngreene** [comment]
Given that the X-Plane 11 and Blender rendering engines are radically different, the sad fact is that there isn't much we can set in the Blender Render viewport to simulate how it will look in X-Plane. X-Plane 11's rendering engine is based around the idea of Physically-Based Rendering, something that seems to only be supported in the Cycles rendering engine which we do not support (nor plan to).

To have Blender give an accurate preview of how something would look in X-Plane we would have to re-implement very large portions of the X-Plane code base, which is something that we will never pursue for obvious reasons.

If you are looking to speed up your workflow, there are ways to organize your projects and files and use shell or batch scripts to automate repetitious file management. In addition, you can leave a feature request for ways to improve the Blender workflow. Someone asked for a Dialog-Box-Free export button in #261 and it was implemented pretty quickly.

Sorry to disappoint,
Ted

**Comment by bsupnik** [comment]
@JasonGilholme  my understanding is that _future_ versions of Blender are going to feature a PBR-style rendering node that is very similar to what everyone expects, e.g. from UE4, Unity, Substance Painter 2, etc. - this will fit well with X-Plane.  

In the past Ondrej and I talked about having buttons to preset materials to be useful for X-plane - both in setting the stuff x-plane looks at to useful defaults to avoid "ATTR junk" in exports and to get the best preview/visualization.

So in the future we could set up the material to use a cycles render that simulates PBR.  Apparently one of them is going to be real time on the GPU, which would be REALLY useful.

For the current release, our goal is just exposure of the settings - our assumption is that you'll use Substance Painter 2 to do your texturing work - you can export an FBX file from blender with your work and then see it with PBR in SP2 - we have an SP2 export preset for x-plane that I'll post.

**Comment by tngreene** [comment]
Ha! Shows how much I know about the state of Blender. Ignore me.

**Comment by JasonGilholme** [comment]
@bsupnik @tngreene Thanks for taking the time to reply.  It's topical as I've just done a small evaluation on the dev version of blender to see if it'd be suitable for our Layout department.  

The online renderer struck me as rather impressive but I'm not sure how exact it would be in comparison to what you've implemented Ben. I'm sure we could get a close approximation and with any luck they'll expose some glsl to us and then we could ensure that the xp11 attrs are represented accurately.

**Comment by lehthanis** [comment]
@bsupnik I've tried google...did the SP2 export preset ever get posted somewhere?
