### ISSUE TITLE
OrderedDict mutated

### ISSUE THREAD

**Issue by xaeop** [der-On/XPlane2Blender#228]
Blender Version
Broken: 2.78c e92f235283

Short description of error
OrderedDict mutated during Iteration when trying to export using Blender2Xplane plugin. 
This bug has history see bug reports #160, #180 & #208. Report #160 has a Python fix which I have tried but doesn't work.

Exact steps for others to reproduce the error
Add material to a cube. Set Layer 1 in Xplane plug in. File->Export->Xplane Object. Enter file name export. Error message : OrderedDict mutated during Iteration

**Comment by JasonGilholme** [comment]
I'm unable to reproduce this. Can you provide a .blend file that's setup and ready to test with?

**Comment by xaeop** [comment]
Hi Jason,

Attached test blender file and a log of the errors I’m getting.

Regards

Andrew

**Comment by JasonGilholme** [comment]
Hi Andrew,

I can't see any attachment on email or on github.  Where should it turn up?

Jason

**Comment by xaeop** [comment]
Hi Jason,

The files are attached to the email. I have repeated the attachment here. The blender file is test.blend and the log file is blender.log.

Andrew

**Comment by JasonGilholme** [comment]
[test.txt](https://github.com/der-On/XPlane2Blender/files/851836/test.txt)

hmmm - still can't see it.  perhaps I don't get attachments via email cause i'm not a collaborator on this repo.  i've uploaded a test text file via my reply directly on github.  Could you try this way instead of via email?

**Comment by xaeop** [comment]
Hi Jason,

Lets try this. Both files in Blender.zip

Andrew

[blender.zip](https://github.com/der-On/XPlane2Blender/files/851863/blender.zip)

**Comment by JasonGilholme** [comment]
Awesome. got it.  thanks.

**Comment by JasonGilholme** [comment]
With your test file I get a valid output, albeit with a warning regarding UV's. I've pasted it below.

Can you provide some environment details?  Blender version, XP2B version, os details etc.

My env details:
XP2B v3.3.12,
Blender v2.78c and 2.76b
Ubuntu-16.04.

Log:
```
INFO: scanning Cube
INFO: scanning Camera
INFO: scanning Point
INFO: 	 Cube: adding to list
INFO: 	 Point: adding to list
INFO: 		 checking animations of Cube
INFO: 		 checking animations of Camera
INFO: 		 checking animations of Point
INFO: Cube: faces 6 | xplaneObject-faces 12 | tris-to-quads ratio   2.00 | indices 36 | vertices 8
INFO: POINT COUNTS: faces 12 - vertices 36 - indices 36
INFO: Using the following reference materials: Material.001
WARNING: Object "Cube" has no UV-Map.
INFO: Writing /home/jase/cubetest.obj
```

**Comment by xaeop** [comment]
Morning Jason,

If you are wondering about the delay in my reply, I live in the United Kingdom so I’m replying to your e-mail this morning. 

I think I have sorted it out. Looking at your XP2B version I compared it to mine which was 3.20.14. I went back into GitHub and discovered I had downloaded the master version which is over two years old.

I removed my version of XP2B and reloaded with 3.3.12 and re-ran the cube test and ended up with the same results as you. I then ran my larger blender file that I was trying to output and that gave me an obj file with no errors.

Please close this ticket as it was down to me not understanding the versions on GitHub.

Thanks for your help.

Andrew

**Comment by JasonGilholme** [comment]
G'day, (I'm an Aussie)

Not a problem. Ideally the default branch would be the main development branch.  In this case it's not.

I suggest using the releases page on github.  This provides a clear way of getting the 'official' version of the released code.

Happy travels.
Jase
