### ISSUE TITLE
No WSYWIG with location transformed objects parented to other objects.

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#233]
Trying to create an artificial horizon. (This worked in the old 3.10 export script).  The inner part is given a LOC animation, and parented to the outer ring, which has a rotation animation.  The animation ALMOST works in X-Plane... only problem is, the exported object is not like it's displayed in Blender. There's an offset, which makes the inner part appear IN FRONT OF the outer ring in X-plane.   

Blender:
<img width="1023" alt="screen shot 2017-03-29 at 6 41 59 pm" src="https://cloud.githubusercontent.com/assets/359923/24481416/bbb30c96-14af-11e7-8514-2f1b9edfef71.png">

X-Plane:
<img width="944" alt="screen shot 2017-03-29 at 6 42 59 pm" src="https://cloud.githubusercontent.com/assets/359923/24481415/bbb22ac4-14af-11e7-8e08-e2913b68fa33.png">

I made sure the object centres were aligned before parenting it to the outer ring. The Outer ring contains three keyframes, two of which have dataref counterpart keyframes, and the third one is just to reset it back to 0º, so that the inner part could be more easily animated. This setup has worked for me for over 30 planes in XP2B 3.10.

Attached is an RV-10 sample plane with only the artificial horizon as its sole object, along with its Blender source file and texture.

[RV-10-XP2B3.3.3Test.zip](https://github.com/der-On/XPlane2Blender/files/880658/RV-10-XP2B3.3.3Test.zip)

I have to have full WYSIWYG support to be able to use this new version of the script.

**Comment by danklaue** [comment]
Also, just noticed that the animation terminations (to prevent center piece from exceeding the bounds of the ring) aren't being respected in v3.3.3 of the script. This works fine in v3.20.  Termination is done exactly as how this part is animated in v3.20, and it exports as expected.

<img width="1050" alt="screen shot 2017-03-29 at 6 59 39 pm" src="https://cloud.githubusercontent.com/assets/359923/24481718/e7670fc0-14b1-11e7-9981-c96f0a849236.png">



(Attached .obj file was exported with XP2B 3.20).
[ArtHorTest.obj.zip](https://github.com/der-On/XPlane2Blender/files/880673/ArtHorTest.obj.zip)

**Comment by danklaue** [comment]
Figured it out.  If object scale is not reset to 1, 1, 1, then an offset is generated.

**Comment by danklaue** [comment]
Not sure if something will be done about this behaviour.... but it definitely is different than in v3.20. And it's not WYSIWYG, which is a big deal, if people don't know about this scaling issue.  I almost authored a plane with a fix in Blender that made it look right in X-Plane, but wrong in Blender. If the script gets fixed, such authoring decisions could break future versions of the project.

**Comment by airfightergr** [comment]
Scale in blender is very basic and works internally. It is one of the most basic properties of an object, at the same level as location and rotation. This is standard blender behaviour. Things like modifiers are depending on that, and I don't think that an export script should reverse or disregard blender core behaviour.
You have 2 options. Or scale in object mode and directly apply scale (Ctrl+A), or scale in edit mode.

**Comment by der-On** [comment]
3.20 was not really supporting scales other then 1,1,1 also. A possible fix to this is to apply scaling to objects during export but this might have strange and unwanted side effects. Scale in Blender applies to the transformation matrix and will affect everything, including animations. However X-Plane does not know scaling at all and such scaling must be "baked" on export which can become a complicated process.

**Comment by bsupnik** [comment]
5670d68b67146af8e68a4632fad762ec85bd7514
