### ISSUE TITLE
Stacking multiple rotation datarefs on the same knob results in a huge location offset.

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#241]
This did not happen in previous versions.  A setting like the following one, intended to create a multi-knob, which rotates in relation to several datarefs, depending on what the knob is selected to alter, should be possible.

<img width="498" alt="screen shot 2017-04-19 at 3 35 45 pm" src="https://cloud.githubusercontent.com/assets/359923/25200979/f8c49764-2515-11e7-9868-7f2d66bbdb76.png">

The result is this:

# 1 Object: Multi_Knob_G500
ANIM_begin
ANIM_trans_begin	sim/cockpit2/autopilot/vvi_dial_fpm
ANIM_trans_key	0	-0.38352901	0.369663	-0.38486499
ANIM_trans_key	100	-0.38352901	0.369663	-0.38486499
ANIM_trans_end
ANIM_rotate_begin	0	0	-1	sim/cockpit2/autopilot/vvi_dial_fpm
ANIM_rotate_key	0	0
ANIM_rotate_key	100	3.99999997
ANIM_rotate_end
ANIM_trans_begin	carenado/g1000/atp/heading
ANIM_trans_key	0	-0.38352901	0.369663	-0.38486499
ANIM_trans_key	1	-0.38352901	0.369663	-0.38486499
ANIM_trans_end
ANIM_rotate_begin	0	0	-1	carenado/g1000/atp/heading
ANIM_rotate_key	0	0
ANIM_rotate_key	1	3.99999997
ANIM_rotate_end
ANIM_trans_begin	sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot
ANIM_trans_key	0	-0.38352901	0.369663	-0.38486499
ANIM_trans_key	0.01	-0.38352901	0.369663	-0.38486499
ANIM_trans_end
ANIM_rotate_begin	0	0	-1	sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot
ANIM_rotate_key	0	0
ANIM_rotate_key	0.01	3.99999997
ANIM_rotate_end
ANIM_trans_begin	carenado/g1000/atp/alt
ANIM_trans_key	0	-0.38352901	0.369663	-0.38486499
ANIM_trans_key	100	-0.38352901	0.369663	-0.38486499
ANIM_trans_end
ANIM_rotate_begin	0	0	-1	carenado/g1000/atp/alt
ANIM_rotate_key	0	0
ANIM_rotate_key	100	3.99999997
ANIM_rotate_end
ANIM_trans_begin	carenado/g1000/pfd/baro/crs
ANIM_trans_key	0	-0.38352901	0.369663	-0.38486499
ANIM_trans_key	1	-0.38352901	0.369663	-0.38486499
ANIM_trans_end
ANIM_rotate_begin	0	0	-1	carenado/g1000/pfd/baro/crs
ANIM_rotate_key	0	0
ANIM_rotate_key	1	3.99999997
ANIM_rotate_end
ANIM_hide	142	143	thranda/sim_scroll_hover
ANIM_show	0	0	thranda/panels/scrollWh
TRIS	93849 495
ANIM_end

Exporting the VERY SAME file from XP2B 3.20 yields this:

ANIM_begin
	ANIM_trans	0.19347097	0.36666298	-0.38486502	0.19347097	0.36666298	-0.38486502	0	0	none
	ANIM_trans_begin	sim/cockpit2/autopilot/vvi_dial_fpm
		ANIM_trans_key	0.00000000	0.00000000	0.00000000	0.00000000
		ANIM_trans_key	100.00000000	-0.00000001	0.00000000	0.00000003
	ANIM_trans_end
	ANIM_rotate_begin	0.00000000	0.00000000	1.00000000	sim/cockpit2/autopilot/vvi_dial_fpm
		ANIM_rotate_key	0.00000000	0.00000000
		ANIM_rotate_key	100.00000000	-3.99999954
	ANIM_rotate_end
	ANIM_trans_begin	carenado/g1000/atp/heading
		ANIM_trans_key	0.00000000	0.00000000	0.00000000	0.00000000
		ANIM_trans_key	1.00000000	-0.00000001	0.00000000	0.00000003
	ANIM_trans_end
	ANIM_rotate_begin	0.00000000	0.00000000	1.00000000	carenado/g1000/atp/heading
		ANIM_rotate_key	0.00000000	0.00000000
		ANIM_rotate_key	1.00000000	-3.99999954
	ANIM_rotate_end
	ANIM_trans_begin	carenado/g1000/pfd/baro/crs
		ANIM_trans_key	0.00000000	0.00000000	0.00000000	0.00000000
		ANIM_trans_key	1.00000000	-0.00000001	0.00000000	0.00000003
	ANIM_trans_end
	ANIM_rotate_begin	0.00000000	0.00000000	1.00000000	carenado/g1000/pfd/baro/crs
		ANIM_rotate_key	0.00000000	0.00000000
		ANIM_rotate_key	1.00000000	-3.99999954
	ANIM_rotate_end
	ANIM_trans_begin	carenado/g1000/atp/alt
		ANIM_trans_key	0.00000000	0.00000000	0.00000000	0.00000000
		ANIM_trans_key	100.00000000	-0.00000001	0.00000000	0.00000003
	ANIM_trans_end
	ANIM_rotate_begin	0.00000000	0.00000000	1.00000000	carenado/g1000/atp/alt
		ANIM_rotate_key	0.00000000	0.00000000
		ANIM_rotate_key	100.00000000	-3.99999954
	ANIM_rotate_end
	ANIM_trans_begin	sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot
		ANIM_trans_key	0.00000000	0.00000000	0.00000000	0.00000000
		ANIM_trans_key	0.01000000	-0.00000001	0.00000000	0.00000003
	ANIM_trans_end
	ANIM_rotate_begin	0.00000000	0.00000000	1.00000000	sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot
		ANIM_rotate_key	0.00000000	0.00000000
		ANIM_rotate_key	0.01000000	-3.99999954
	ANIM_rotate_end
	ANIM_hide	142.00000000	143.00000000	thranda/sim_scroll_hover
	ANIM_show	0.00000000	0.00000000	thranda/panels/scrollWh
	TRIS	61512 495
ANIM_end

Notice how all trans values are  0, 0, 0 in the old script. In the new script, they're all massively offset.

**Comment by danklaue** [comment]
I tried zeroing out the trans_keys in the sample exported in 3.3.3, but all that did was centre the knob in the middle of the scene (At the centre of the aircraft).  Then, I tried pasting the line:

ANIM_trans	0.19347097	0.36666298	-0.38486502	0.19347097	0.36666298	-0.38486502	0	0	none

into the object exported by v3.3.3, but to no avail.  I can't tell which syntax is responsible for the offset.

**Comment by tngreene** [comment]
This is a really good lead. Would it be possible post a blender file as a sample, like you did in #219 ?

**Comment by tngreene** [comment]
Copy Paste from #219, cause its important:

> Now,
>
> I can't exactly make sense of what's happening here. But what it seems like to me is:
>
> -The common "trigger" is, using two datarefs on a single animation.
> -3.20 exports this properly.
> -3.30 makes a distinction between the parts that are parented to an empty (no matter if rotated or not), and those that aren't parented to an empty... although this is inconclusive in my tests.
> -3.30 seems to make a distinction between whether "LocRot" or "Rot" is used.

**Comment by tngreene** [comment]
- So, in my own testing, I created a test case of identically animated cubes, 3 with 1 data ref, 3 with 2. Each of the three's anim_type was set to loc, locrot, or rot.
- In one file, there are no empty parents. In the other, each has its own identical empty parent with a large offset.
- Each mesh is in its own layer, therefore, each has its own .obj

Differences:

In all cubes with an empty parent, there is an unexplained ANIM_trans directive.
	```ANIM_trans	-0.00000763	0	0	-0.00000763	0	0```

For the case with 2 data refs, with its anim_type set to 'rot', the offset is quite wild.
	```ANIM_trans	-131.01005554	-0.40415746	-0.90874255	-131.01005554	-0.40415746	-0.90874255```

The empty parent's object information
Location -125.000, 0, 0
Rotation 0, 0, 0
Scale 1,1,1

in all frames for all cubes.

Where is that .0000763 coming from? floating point type issue?

**Comment by tngreene** [comment]
See the test materials here:
[241_simple_case_test_samples.zip](https://github.com/der-On/XPlane2Blender/files/962999/241_simple_case_test_samples.zip)

**Comment by tngreene** [comment]
The last time code relating to making decisions based on anim_type if it were location/rotation/ or locrot was  

> Date:		2 years ago (7/28/2015 9:37:48 AM)
> Commit hash:	461dc5166300c1f28abdcdf7e7eaa9806786c4a5
> 
> removed verbose print()
 
The next commit
> Author:		Ondrej Brinkel <info@anzui.de>
> Date:		2 years ago (7/28/2015 10:30:38 AM)
> Commit hash:	3d5eb9cfa1ae49320610238241b58fd2e24bfcc4
> Children:	1ba1afb792
> Parent(s):	461dc51663
> 
> written naive to test for exporting files using blenders UI (operators)

removed such code and it was never fully replaced.

**Comment by tngreene** [comment]
Frustratingly, creating another simple test case (see attached), I am unable to recreate the large offset. In addition, for that previous simple test case, changing the cube in Case_2_data_ref_rot_w_empty's parent with another one, swapping for a duplicate, and shifting of layers it resided on (the last layer seemed to be the most prone to breaking) seemed to break the test case and stop reproducability.

What ever the issue is, it seems awefully unstable, and could be a problem with Blender itself.

**Comment by danklaue** [comment]
If it's a problem with Blender, then testing on different/older versions of Blender should reveal that with more consistency, or not?

**Comment by tngreene** [comment]
The issue with 241_simple_case changing when I change a parent turned out to be that the matrix_parent_inverse had gotten changed to something bizarre.

False leads so far:
- Rot/Loc/Locrot does not matter
- 241_simple_case weirdness was not the huge offset or bug we are looking for
- Blender version seems not to matter
