### ISSUE TITLE
Optimization: Dumbly animated parents should not write out ANIM_begin/end

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#245]
In the case of having an animated parent whose animation is not meaningful (going from 0,0,0 to 0,0,0, rotating from 0,0,0 to 0,0,0), it should not write out "ANIM_begin/end"

**Comment by bsupnik** [comment]
I think this is fixed as of v3-3 around 5fc6d0ba1995a359631b6c873e71a1e015db68b2
