### ISSUE TITLE
Animation with rotation but not translation needs matrix transformation model changed

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#246]
Suppose the following situation

You have an animated parent, and an animated child mesh. It has keyframed animation for the rotation but not translation: The translation is static throughout.

Currently this is bugged: The translation is not put into the pre-animation pose and is instead gets written to the keyframe table causing large offsets. This was they problem with #219!

**Comment by tngreene** [comment]
This was believed to be fixed with ed034c3327089a62c5

**Comment by danklaue** [comment]
With the latest commit, a new problem has arisen: a stacked animation in a bone that previously exported OK, no longer exports OK.

Suppose the following situation: 

You animate a yoke, but only use ONE bone. You stack the linear animation and the rotational animation, so you have two datarefs (Pitch and Roll) on the same bone.  With the latest commit (7e87e01), it only actually exports the first one.  Previously, it exported correctly.
