### ISSUE TITLE
Show/Hide animations don't work when stacked

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#251]
Consider the following scenario:  you want to animate a spinner, and you have 3 levels of motion blur you'd like to display, depending on RPM.  So you use 3 separate spinner objects, each with a show-hide animation on it.

In the old version of the export script, you could set it up as follows:

**Low-speed spinner object:** 

- hide when "prop_rot_rad_sec" dataref is between 22 and 1000.

**Mid-speed spinner object:** 

- hide when value is between -20 and +22

- then hide when value is between +28 and 1000.

**High-speed spinner object:**

- hide when value is between -20 and +28.

In this case, the Mid-speed spinner object does not interpret the stacked show/hide commands properly.  This affects legacy projects, but also severely limits what you can do with, for instance, annunciator panels, knob animations, etc.

I'll work on a simplified sample file, and submit it as a response.

**Comment by danklaue** [comment]
Here's a sample plane to illustrate the problem.

[TestPlaneStackedShowHide.zip](https://github.com/der-On/XPlane2Blender/files/1029263/TestPlaneStackedShowHide.zip)


The animation stack of the problematic object looks like this:
<img width="571" alt="showhidestack" src="https://cloud.githubusercontent.com/assets/359923/26454235/21d245d4-412c-11e7-9182-ba8dd7a0f2c5.png">

Problem with this export:
Mid-speed spinner doesn't hide at high prop speed.

Expected behaviour:
Mid-speed spinner should hide at high prop speed.

If you export the same Blender file using XP2B 3.1, it works as expected: middle spinner animation is hidden at high speeds.

**Comment by danklaue** [comment]
Comparison of how XP2B 3.2 exports this file, vs. how v3.3 exports it:

v3.2.14:
[SpinnerExportedWithXP2B_3.20.14.obj.zip](https://github.com/der-On/XPlane2Blender/files/1029285/SpinnerExportedWithXP2B_3.20.14.obj.zip)

v3.3.13:

[SpinnerExportedWithXP2B_3.30.13.obj.zip](https://github.com/der-On/XPlane2Blender/files/1029286/SpinnerExportedWithXP2B_3.30.13.obj.zip)

**Comment by tngreene** [comment]
Possibly related to #219, #246, #247. Expect a new build soon from @bsupnik.

**Comment by danklaue** [comment]
Fixed in 0b9380c.
