### ISSUE TITLE
Error when exporting

### ISSUE THREAD

**Issue by gnarlybacon8r** [der-On/XPlane2Blender#254]
When I attempt to export an xplane file, I am shown with an error message for the file _xplane_export.py_ saying that line 59 and line 129 does not have permission

**Comment by gnarlybacon8r** [comment]
Actually, i fixed that I just want to be able to import and nothing says how

**Comment by tngreene** [comment]
XPlane2Blender is unfortunately a misnomer. When der-On started the Blender +2.50 project several years ago there was an idea to do both, however, he found it was easier and more useful to build the exporter first. As such, there really isn't an import .obj->.blend function in this script.

If you would like, you may be able to download an older version of Blender ([2.49](http://download.blender.org/release/Blender2.49/)) and the old version of the [script](https://github.com/Marginal/XPlane2Blender).

From there you could theoretically import an OBJ into Blender 2.49, save the .blend file, open it up in a later version of blender. This is probably going to result in very broken geometry and none of these projects are receiving support or upgrades.

I'm sorry you won't be able to import now, or in the foreseeable future.
