### ISSUE TITLE
Scaling issues: Non - WYSIWYG export

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#257]
Consider the following scenario:

Three identical objects have differing underlying scale values in Blender. They look the same in Blender:
<img width="1039" alt="screen shot 2017-05-30 at 7 02 38 pm" src="https://cloud.githubusercontent.com/assets/359923/26610011/9764ddce-456a-11e7-8785-f097966257dc.png">

When exported, however, they look like this in X-plane:

<img width="856" alt="screen shot 2017-05-30 at 7 03 19 pm" src="https://cloud.githubusercontent.com/assets/359923/26610021/ad1c2ab4-456a-11e7-9906-357f0089feea.png">

These objects have been scaled to different scale values in Blender, but in edit mode, their respective meshes have been made to be identical across the board.

Not only do these parent objects export at different scales (NOT WYSIWYG behaviour), but also, the children of these parent objects are offset.  Their animations also seem scaled.  The children objects are no longer co-planar, and have huge offsets.

The centre artificial horizon is the one that is done "Correctly", i.e, the scale of the object is set to 1, 1, 1, and the mesh has the correct size.  The other two have non-standard scales, but their meshes have been adapted.

Here's a Blender file of this scenario:

[ScalingTest.blend.zip](https://github.com/der-On/XPlane2Blender/files/1039960/ScalingTest.blend.zip)

**Comment by danklaue** [comment]
One thing of note about this bug is this: if an object is scaled in Blender, the exporter ignores the scale, and exports it as though no change was made to the scale of the object.

(In other words, if I were to take the middle artificial horizon, and scale it down in Blender, to say, 0.5, 0.5, 0.5, the exported object, when viewed in X-Plane, looks as though its size had not been altered.)


AND: the child object of such a scaled object also behaves as though the parent hadn't been scaled at all.   So: creating a parent-child assembly, then resizing the parent has NO effect on the final output.  But changing the order, i.e., parenting an object to an already resized parent object WILL result in an offset.

Again, it is only when the child is parented to a non-1,1,1 scaled object, that an offset is generated in the child animation.

**Comment by bsupnik** [comment]
This is a duplicate or is related to #233 - the one known remaining issue is when non-zero scales are used.

**Comment by bsupnik** [comment]
5670d68b67146af8e68a4632fad762ec85bd7514
