### ISSUE TITLE
Need "EXPORT" directive support

### ISSUE THREAD

**Issue by bsupnik** [der-On/XPlane2Blender#262]
This is a new feature for 3-4 that is necessary to replace the 2.49 blender's workflow.

An EXPORT directive is an _unofficial_ OBJ header directive of the form

EXPORT lib/airport/trucks/catering_truck.obj trucks/catering_truck.obj

The export directive is NOT understood by the OBJ reader - rather a post-processing tool "gathers" them out of the OBJs and into a library.txt file.

To support this, each export "layer" that specifies a file path should have an _option_ to include a library path.  When this option is used, the EXPORT directive is written to the header.

Where does the physical path come from?  It's the path that the file is actually exported to!

Here's where things get slightly tricky: in order to write the right physical path, the exporter must find the _parent scenery pack_ that the file is contained within.  The process is basically this:

1. Find the FULL physical file path that the OBJ will be exported to.
2. Search for one of "Custom Scenery" or "default scenery" as a path element.  This is the scenery directory.
2a. If neither are found, fail export.
3. Remove every path before the scenery directory, the scenery directory, and one directory element after.
3a. If there are not enough directories to do this before the OBJ file, error.
4. The remaining path is the physical path.

Example: the lib path is lib/g10/cars/car.obj
Example: an object is exported to /code/x-plane/Custom Scenery/Kansas City/cars/honda.obj

We locate Custom Scenery.
We strip /code/x-plane/Custom Scenery/Kansas City/.
The physical path is cars/honda.obj
The export directive is

EXPORT lib/g10/cars/car.obj cars/honda.obj

**Comment by bsupnik** [comment]
NOTE: each layer needs to be able to support _multiple_ export directives...so this needs to be an array with the user able to add more.

**Comment by tngreene** [comment]
[ ] - Create UI for per X-Plane layer of an array of multiple export directives
[ ] - Create algorithm for finding full physical path to reducing it to the relative physical path
[ ] - Create EXPORT directive in OBJ Header
[ ] - Create unit test
[ ] - Document this unofficial directive's existence in the exporter somewhere

**Comment by tngreene** [comment]
Basic UI created 87c7c2f87b84537580612ab2e7521f628bdb14e2

**Comment by tngreene** [comment]
Where should this get documented? developer.x-plane.com? On the wiki? In the docsbook?

**Comment by tngreene** [comment]
It has been documented in the manual
