### ISSUE TITLE
Problem with exported lights

### ISSUE THREAD

**Issue by kucoman** [der-On/XPlane2Blender#264]
I just tried to export the Rotate MD-80 with the last version of the exporter. Only one issue came up until now. The exported exterior lights are different than with previous versions of the exporter.

Attached are a test blender file, and two exported objs, with the different exporters. I have used version 3.20 (this is working ok) and the last version  3.3.13. (I took it from here 
https://github.com/der-On/XPlane2Blender/tree/259-fix-attribute-reset)

In the last version of the exporter, the lights point somewhere unexpected.

[Rotate-MD-80-lights-test.zip](https://github.com/der-On/XPlane2Blender/files/1092103/Rotate-MD-80-lights-test.zip)

The exterior lights you find in the blend file, correspond to the configuration that was found to give better results in the former 3.20, that is, pointing the lights using bones to direct them, and the internal light's parameters to control aperture, color, ...
I am not sure if a better workflow is recommended now with the new versions of the exporter.

Please, let me know if you need me to provide more information.

**Comment by bsupnik** [comment]
I think the latest commit (b275b8f339af96a8df72fd97647ad235d34913eb) on the v3-3 branch should fix this.  Please try the latest v3-3 branch and let me know if the bug is fixed or not!

**Comment by kucoman** [comment]
I have tried this with v3.4.0-beta.4, and the problem with the lights persist in the Rotate MD-80.
Let me know if there is any additional info I can provide.

**Comment by kucoman** [comment]
In case I was not clear. Location of the lights is ok. It is rotation that is not working as expected. Lights are pointed to the front no matter what the bone's direction is. And, apparently it only happens to the lights attached to non-animated bones, but I have not been able to confirm this point.

**Comment by tngreene** [comment]
Fixed with 9329a8d.
