### ISSUE TITLE
Weird animation bug: static discharge wicks with loop don't export properly

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#265]
This exported fine in XP2B 3.20.14.  It's supposed to vibrate a little bit with every meter that is travelled forward.  There are loops in the animations, but the latest XP2B export script doesn't seem to respect these loops.

Here's the .blend file:

[StaticWicksTest.blend.zip](https://github.com/der-On/XPlane2Blender/files/1093491/StaticWicksTest.blend.zip)

**Comment by bsupnik** [comment]
The bug here is that the current exporter is not writing key frame loop directives for armature/bone-based animations.  Amazingly, NONE of the test suite covers this.  I have a local fix and will check it in once I have a few test cases.

**Comment by bsupnik** [comment]
Fixed on the v3-3 branch via this commit: 107b3e37744762ce67b26a11f4dc8db726228051
