### ISSUE TITLE
Only the first HIDE - Animation works

### ISSUE THREAD

**Issue by Colimata** [der-On/XPlane2Blender#266]
Hi,
if in the objects tab, multiple HIDE animations are added, only the first one works.
Very often more than one is needed. It's a reliable way to store "logic" directly inside the OBJ.

Thank you guys for your commitment to this exporter. Really appreciated!
Florian
COLIMATA

**Comment by bsupnik** [comment]
Hi,

Can you please attach a small .blend file that demonstrates the bug?

**Comment by Colimata** [comment]
[HIDE_bug.zip](https://github.com/der-On/XPlane2Blender/files/1127140/HIDE_bug.zip)

Here's a small file the illustrates the issue (blend + obj file). 
3 HIDE animations are defined, only 1 gets exported.
blender 2.78c. Tested with various versions of the latest exporter (3.3.12 ?). Also tried a branch modified just 13 days ago. Same result.
![hide_bug](https://user-images.githubusercontent.com/29890711/27901487-90451704-6232-11e7-877a-ac5279bae2d3.png)

Hope to not make you loose time. It's just that I would really need this for my projects.
Thanks, guys!

**Comment by bsupnik** [comment]
This bug appears to be fixed as of this commit
107b3e37744762ce67b26a11f4dc8db726228051
on the v3-3 branch.
