### ISSUE TITLE
Clean and condense the settings layer menu

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#267]
This is our current layer menu for a scenery's layer.
The Blender UI can make your eyes glaze over this problem by hiding the lines, but I think it is becoming very unusable, especially now that #262 is requesting another large UI feature in this panel.

Some particular areas of concern are
- Lack of consistent pattern of nesting: Slope limit is in a nest all by itself, Tilted is not?
- More nesting than required: The custom properties are triple nested which looks ugly and reduces the space inside the text fields
- Inconsistent labeling: We have "Textures" as a label for the next settings, but that's it for the very useful concept.
- Inconsistent in group or out of group: Everything related to layer groups is inside its own little nest, but Custom Properties and it's button are outside of the Custom Properties group.
- Very large amounts of vertical space used: We could put some items like "Cast shadows" and "Shadow cutoff on the same horizontal level?", or organize things into 2x2 grids. Layer Group's enums are short, Layer Group Offset is an integer, they could be put on the same line without trouble. We could also put things in groups under disclose arrows and save on vertical space that way.
- Inconsistent casing: This is small but annoying, ``Somethings Features Title Cased``, ``Somethings only have the first letter capitalized``. This looks unprofessional, but also makes for a bumpy read.

All of these are easy changes, its just a matter of choosing a UI standard and sticking with it. It may not even move familiar UI elements around too much. I think a new release and new coat of paint would go nicely together.

```
 _____________________________________
|                Layer 1              |
|                                     |
|[ ] Export                           |
|[ ] Debug                            |
| Name:         ______________________|
| Type:         [Scenery Object]      |
|Textures                             |
| ___________________________________ |
||[x] Autodetect Textures            ||
||___________________________________||
| ___________________________________||
|| Levels of Detail: [none          ]||
|| _________________________________ ||
|||Max. Draped LOD:             0.00|||
||___________________________________||
| Slung Load weight              0.00 |
| ____________________________________|
||[ ] Slope limit                     |
| ------------------------------------|
| [ ] Tilted                          |
| Required Surface:   [Any           ]|
| ____________________________________|
||[ ] Cast shadows                    |
||[ ] Shadow cutoff                   |
| ------------------------------------|
|_____________________________________|
| ___________________________________ |
||Layer Group: [None]                ||
|| ___________________________       ||
|||Layer Group Offset:      0 |      ||
|| ---------------------------       ||
|| Draped Layer Group: [None]        ||
||  _________________________________||
|| |Draped Layer Group Offset       0||
||___________________________________||
|_____________________________________|
|                                     |
| Custom Properties    [Add Property] |
| ___________________________________ |
|| __________________________________||
|||Name: [        ] Value: [       ]|||
|||---------------------------------|||
|||Name: [        ] Value: [       ]|||
|||---------------------------------|||
|||Name: [        ] Value: [       ]|||
|| --------------------------------- ||
| ----------------------------------- |
|_____________________________________|
```

**Comment by tngreene** [comment]
Questions to answer:

- What elements can we group together?
- What less used elements can we put lower in the layer's section?
- How do we separate different collections of properties? By nested groups? With dividers? Under disclosed groups? (like LODs)
- How do we label collections of properties? With a label?
- How do we save on vertical space? Smarter layout? More hiding when not needed?
- Title Case or Sentence case?

**Comment by tngreene** [comment]
It would probably be very very good to copy the existing Blender conventions.

**Comment by bsupnik** [comment]
Here's an approximate top-level grouping, based on category and frequency of usage:

Basic:
 - Export Name
 - Export Type
 - Auto-Detect Textures group

LOD Group:
 - Levels of detail count and LOD sub-objects
 - Draped LOD distance

Scenery Properties Group:
 - Layer Group
 - Draped Layer Group
 - Casts shadows*
 - Slope Limits*
 - Tilt
 - Require Surface

Advanced:
 - Slung Load Weight
 - Custom Properties
 - Export (e.g. this should be always on and no one changes it 99% of the time)
 - Debug



NOTES on this:
1. Slung load weight is "buried" because it's not commonly used, as it's not used for EITHER scenery or airplanes - only for misc cargo objects.
2. Custom properties are buried because we want to move away from users needing them and toward the exporter being "caught up" to x-plane -- custom properties existed to let users try new things without a good exporter.
3. Casts shadows and shadow ratio should probably be material properties and not object properties?  This needs investigation, including analysis of backward compatibility.

**Comment by tngreene** [comment]
Awesome, thank you!

**Comment by tngreene** [comment]
After all that cleaning on 267-clean-ui I'd call this finished.
