### ISSUE TITLE
Merge 'v3-3' into master, finally.

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#268]
The last time that something was pushed to master was 'v3.20.14', 4/15/2015. That was literally over 2 years ago. Not only is it confusing to newcomers I think it looks bad and we're potentially missing out on some nice github features that only interact with the master branch.

In 2 years we've developed some great feature complete, bug tested, and shipped versions of 3.3. As soon as we ship v3.4.0, can we please get back to using the master branch like a proper git flow should use?

**Comment by arb65912** [comment]
Yes, as an average user, not familiar with GitHub features, it was very confusing to me what version to use.
I was using master for a long time till I was told by Ben S to use branch 3.3

**Comment by bsupnik** [comment]
Ted, let's do this:
1. When the 3.4 work is feature complete, merge to master.
2. Start a new _release branch_ for 3.4 since we'll start beta.
3. New commits to 3.4 to fix bugs get merged to master frequently, like we do for WED.

**Comment by tngreene** [comment]
v3-3 merged, v3-4 created, new git-flow started!
