### ISSUE TITLE
Dialog-Box-Free-Export button does not show up in Root Object mode

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#270]
Our new instant export button feature does not show up in the UI while in Root Object Mode. Should it stay in scene settings no matter what or appear in root object?

**Comment by bsupnik** [comment]
Yes. We want to have a one-button click to export ALL of the root objects at once.

**Comment by bsupnik** [comment]
(This should be fixed before the one-button export is considered ready to ship.)

**Comment by tngreene** [comment]
Good news! I was incorrect in the first place. This wasn't a bug ever.
