### ISSUE TITLE
Documentation link does not open it directly

### ISSUE THREAD

**Issue by arb65912** [der-On/XPlane2Blender#271]
It is probably irrelevant but when you click on the link for documentation, it takes user to another link saying that documentation has moved and clicking it opens documentation.
Would it disrupt GitHub structure if documentation link was a direct documentation link?
![01 documentation link 01](https://user-images.githubusercontent.com/16321070/28486311-e2bb274e-6e4e-11e7-9ebd-188b9f8ffc74.JPG)
![01 documentation link 02](https://user-images.githubusercontent.com/16321070/28486312-e631a7fe-6e4e-11e7-95e9-00deae8f361a.JPG)

**Comment by tngreene** [comment]
Unfortunately, there is is no way for us to allow users to click on the word "Wiki" and have it bring them directly to the documentation. In addition, the wiki has some valuable stuff in it that we want people to access (until things get moved and pushed around and its all in one place one day. If we actually want that.)
