### ISSUE TITLE
Documentation v3.3 Installation - Detailed Notes suggestions

### ISSUE THREAD

**Issue by arb65912** [der-On/XPlane2Blender#272]
In chapter **Customizing Blender/Preferences to change** there is suggestion:

**Input: select with: pick left.**

I understand that it is a personal preference but majority of the Blender tutorials suggest to leave default behavior (select with right mouse click) as the interface was designed for speed working this way ( for right handed users of course).
I would either get rid of that suggestion or at least add comment that it is not really recommended.

**Comment by tngreene** [comment]
I would be willing to get rid of anything that isn't XPlane2Blender specific and replace it with links to better tutorials. "Select with: pick left." is not necessary for XPlane, and anyone who is just starting out in Blender is likely reading other tutorial materials.

Any documentation we have is documentation we have to support. I vote to cut this and replace it with links to proper tutorials other people upkeep.

Anyone have any feedback on what new XPlane2Blender users need for orientation? Picking some random users: @alxunru @danklaue @arb65912

**Comment by tngreene** [comment]
The page in reference is https://der-on.gitbooks.io/xplane2blender-docs/content/v3.3/33_installation_-_detailed_notes.html

**Comment by arb65912** [comment]
Taking into the account the number of Blender learning sources, my suggestion was just to cut the suggestion about left click assign for selecting.

Links to better tutorials might expire with time and the Xplane2Blender documentation should be always updated.
I assume that after resolving the present Issues, the plugin will not grow in a very high rate to make documentation updating task tedious and time consuming.

Of course it is another instance of user preferences ( having links to better tutorials).

I like the idea assuming that links are properly picked but I am afraid that they will expire relatively fast.

**Comment by tngreene** [comment]
Related to #286
