### ISSUE TITLE
Upgrade Loc, Loc/Rot, and Rot to "Transform" aka None

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#280]
Currently, the anim_types "loc","loc/rot", and "rot" are useless. Our matrix transformation model is sufficient enough that you do not need to explicitly declare which animation types are going to get exported. Therefore to clear up confusion those three options will be condensed to "Transform" in the UI, since in the code base they are all ignored anyway. Existing Blend models should get upgraded from those values to "transform" aka nothing to not have straggling invalid data in .blend files.

**Comment by danklaue** [comment]
I've been shafted by a change to this very segment of the "Loc/LocRot/Rot".  I changed my planes to adapt to the way it is now, and would HATE to have to do it to all 50 planes again.

Besides, there is a situation where it is important to have the "ROT only"  variable: drifting spinner cones.

**Comment by tngreene** [comment]
The thing is, that this no longer matters, and has been this way for a long time. There is no where in the code base where "loc", "loc/rot", or "rot" are mentioned. It is all auto detected by the matrix transformation classes and taken care of. Removing this from the UI would remove people wondering what they are for.

**Comment by tngreene** [comment]
The only thing that matters according to the code base is "show","hide", or neither (aka autodetect transformations)

**Comment by danklaue** [comment]
OK, in the past there was a problem with looping rotations, where "LocRot" also caused unintended location transformations on an object like a spinner cone that used the prop rotation dataref, which goes quite high in terms of numerical value.  In the .obj file, the keyframed values for location were not identical, resulting in a gradual locational drift of the cone. (Non-identical values are presumably the result of floating point imprecision.

**Comment by tngreene** [comment]
Upgraded in e8b417334675564843b7e080e73f9c79171d1888
