### ISSUE TITLE
HIDE animation values hidden

### ISSUE THREAD

**Issue by Colimata** [der-On/XPlane2Blender#288]
If there was more than one HIDE animation set on the previous exporter (3.3.13), its values now are neither shown nor exported anymore after the installation of the 3.4.0 exporter. (See file attached). 
When HIDE is set back manually inside "Animation type" the values come back. 
The problem is that I have more then 600 of those...
![showhidelost](https://user-images.githubusercontent.com/29890711/29205832-68aea3c2-7e7f-11e7-9b2e-b14beeea7225.png)
Here's a small blender example file:
[Show Hide Lost.zip](https://github.com/der-On/XPlane2Blender/files/1217259/Show.Hide.Lost.zip)

blender 2.78c portable version installed on D: drive
exporter 3.40 beta 1

Uninstall of the previous exporter was done by deleting the "io_xplane2blender" folder in "...scripts/addons". 

Keep up the great work, appreciated.
Florian
COLIMATA

**Comment by tngreene** [comment]
I think I figured it out, but I'm not sure how this happened. Somehow your file's XPlane2Blender version got changed to 3.4.0 but didn't properly have it

's datarefs properly updated to reflect the change from Loc/Rot/LocRot->Transform. That means that it would never get updated again until 3.4.1!

Try this new build. It includes a button called "Re-run Updater" in the Plugin Development Tools section (bottom of scene tab, enable checkbox to access). Click that and you should see everything get fixed, I think.

[io_xplane2blender_3_4_0_b1_rerunbtn.zip](https://github.com/der-On/XPlane2Blender/files/1218645/io_xplane2blender_3_4_0_b1_rerunbtn.zip)

**Comment by Colimata** [comment]
I check this. Thanks meanwhile.
Florian
COLIMATA

**Comment by tngreene** [comment]
I tried duplicating creating a file with a single animated cube, same datarefs, same animations, in 3.3.13, then getting it to change it's version without also updating the animation types. I can't duplicate it.

Can you go into any more detail about how you made this file and its interactions with exporter versions?

- Created new file in XPlane2Blender version 3.3.13, Blender 2.77
- Saved file as my_anim_test.blend
- Opened file in XPlane2Blender version 3.4.0, Blender 2.78
- Updater ran, animation types are correct

Did you append or link data from blend file to another? Did you maybe go into Scene->Custom Properties->XPlane2Blender and manually edit the version?

**Comment by Colimata** [comment]
**The new build solves!** All values are back right out of the box. 

**Creation:** 
Yes, could be that parts of the file (also some X-Plane settings) have been created in 2.77. 
Before the 3.4.0 installation, however, the file was saved with 3.3.13 since the version before was not able to export multiple HIDE animations. No other hacks applied.
Then 3.4.0 was installed -> SHOW/HIDE animations hidden with the first exporter build.

**Export test to x-plane succeeded.** 

Great job! Thanks!
Florian
COLIMATA

**Comment by tngreene** [comment]
Did you have to use the "Re-run Updater" button or did it just work?

**Comment by Colimata** [comment]
Worked right out of the box. Opened the file and the values were there.
