### ISSUE TITLE
3.4.0 beta 1 export error "no attribute filename_ext"

### ISSUE THREAD

**Issue by Colimata** [der-On/XPlane2Blender#289]
From time to time, after starting the exporter from the drop-down menu the following error shows up:
![export_error](https://user-images.githubusercontent.com/29890711/29206197-198bdfa6-7e81-11e7-950a-32b7748c924c.png)
While the file sometimes exports without errors, on the second or third attempt it comes up. The error does not show up using the new export button.
Here's an example file:
[Show Hide Lost.zip](https://github.com/der-On/XPlane2Blender/files/1217284/Show.Hide.Lost.zip)

Could have to do with issue #288 . Although I tried to complete the missing HIDE values manually. SAme result.
blender 2.78c portable installed on D:
exporter 3.4.0 beta 1

Best regards
Florian
COLIMATA

**Comment by Colimata** [comment]
Parts of this file (including some x-plane settings) could have been created in blender 2.77.
Last save was with exporter version 3.3.13.
Hope this helps.

**Comment by tngreene** [comment]
Try this one out.

[io_xplane2blender_289.zip](https://github.com/der-On/XPlane2Blender/files/1220617/io_xplane2blender_289.zip)

**Comment by Colimata** [comment]
Yes, this one works. It does not show this issue. Not once. Even on very complex files.

**Comment by tngreene** [comment]
Closed in f7bc475a62b817207ee74552237baf9ff952f77d, included in beta.2
