### ISSUE TITLE
Export objects using 1-Click button fails: Must Create X-Plane Layers first.

### ISSUE THREAD

**Issue by myachinyouri** [der-On/XPlane2Blender#291]
Linux Ubuntu 16.04LTS, Blender 2.78c. Issue with export new object, for example a Cube in Layers mode. Hitting the 'Export Objs' button = ERROR: You must create X-Plane layers first. However, an old Blender's objects, where these XP layers has been done, are exported successful.

**Comment by tngreene** [comment]
Try this version and see if you are able to see the Add X-Plane layers button again.

[io_xplane2blender_3_4_0_add_layers_btn_fix.zip](https://github.com/der-On/XPlane2Blender/files/1222677/io_xplane2blender_3_4_0_add_layers_btn_fix.zip)

**Comment by myachinyouri** [comment]
Works perfectly when exporting a new Cube.blend to Cube.obj by using a button 'Export OBj's' and by using  item File>Export>X-Plane Object .  I see the all 20 Layers again. Thanks.

**Comment by tngreene** [comment]
fixed with e40dd7da9d86daee3699c98504366b773b61532a

I have to say it somewhere cause I missed it in the commit log, but the trouble with the layers button disappearing wasn't a python glitch, it was a variable that was deleted

I deemed the pattern
row = layout.row()
row.whatever()
row = layout.row()
row.whatever()
to be excessive, and instead reduced it to 
layout.row().whatever()
layout.row().whatever()

however this mean farther down the variable row didn't exist. Somehow the UI didn't emit an exception, it just swallowed it, and since all my test files and my start up files already had X-Plane layers, I didn't catch that there could be a problem.

This was the fix.
``
-            row.operator('scene.add_xplane_layers')
+            layout.row().operator('scene.add_xplane_layers')
``

this just begs the question "Why do we even have a button?!" #274 

somebody please tell me if I'm missing something about why we need this button.

This fix will be in beta.2

**Comment by arb65912** [comment]
I understand that users have different needs but for me the button does not not do much (as for aircraft developer, maybe for scenery it works differently).
All created objects need to be in aircraft main folder and objects sub-folder so having .obj file in the same folder as .blend file seems to be an extra unnecessary step to me.

**Comment by tngreene** [comment]
Can you describe the folder structure and output you'd like to see?

For instance, if I was working on a Plane I might want a file structure like this (completely making this up).

```
My Plane
|__my_plane.blend
|__Wings
     |_left_wing.obj
     |_right_wing.obj
|__Cockpit
     |_buttons.obj
     |_seat.obj
```

**Comment by tngreene** [comment]
One feature of giving the layer/root objects names is they can be used to place OBJs in specific folders. In the above example I would go into my_plane.blend, and give the layer names

- Wings/left_wing
- Wings/right_wing
- Cockpit/buttons.obj
- Cockpit/seat.obj

and on export those folders would be created (if they didn't already exist) and the .obj's written in the correct place.

**Comment by arb65912** [comment]
Below is my Blender Layers structure. Note layer CRJ-700_cockpit which is exported to aircraft main folder.

![blender layers](https://user-images.githubusercontent.com/16321070/29338893-86e55fa2-81e5-11e7-8e89-5ab17b81fdcb.JPG)

Below you see aircraft structure folder and objects sub folder.

![aircraft folder structure 01](https://user-images.githubusercontent.com/16321070/29338938-b9bc9256-81e5-11e7-8817-b68faf53270d.JPG)

![aircraft folder structure 02](https://user-images.githubusercontent.com/16321070/29338947-c12e740a-81e5-11e7-8809-2c190f3570b8.JPG)

**Only CRJ-700_cockpit.obj** from Layer 01 is exported to **main aircraft folder**, all other layers are exported to "objects" sub-folder.

I would like to be able to set layer names so when I export visible layers, the structure I described would be preserved.
It is not bad now as I usually export only one layer I have made changes to using File/Export/X-Plane_Object from pull down menu.

**Comment by tngreene** [comment]
In layers mode, XPlane2Blender takes the names of it's objs from it's X-Plane layers panel, not these named layers that come from another add-on.

In the settings for Scene->X-Plane->Layer 1, Layer 2, Layer 3, etc

Try these names

```
CRJ-700_cockpit
cockpit/cockpit01
cockpit/cockpit02
cockpit/cockpit03
cockpit_3d/cockpitmain
cockpit_3d/cockpitsides
...
airfoils/wings
```
This will automatically create and place the folder structure you'd like. I think you get the idea.

If you'd want to get even more specific, you could specify any number of folders
``
landing_gear/left/wheel_cap_l
landing_gear/right/wheel_cap_r
``

How many of your projects use these named layers?

**Comment by arb65912** [comment]
Thank you, I will try tonight.

With these new layer names, what folder do I specify from File/Export/X-Plane_Object when asked for location?

This project is my first one using named layers.

**Comment by tngreene** [comment]
Gain, that named layers addon you showed in your screen shot will NOT affect where the obj files go. The only way to affect that is by using X-Plane's Layer names feature.

The point of the button is that you do not need to use the file picker. Every visible layer (as controlled by Blender's 3D Viewport.)

**Comment by arb65912** [comment]
OK, last question before I try.
Layer Name has to have full path to the exported object including drive, correct?

**Comment by tngreene** [comment]
No, it cannot be a full path name. It must be relative to the .blend file.*

For instance if I was working on a fancy park bench saved at ``C:\Users\Ted\Projects\park_bench.blend``

Instead of 

``
C:\Users\Ted\Projects\park_bench\railings\fancy_lettering
```

I would just use

``railings\fancy_lettering``

This was a deliberate choice to not allow "absolute" paths. This enforces an easier time sharing files between people

**Comment by arb65912** [comment]
OK, I think I finally understand what relative paths mean ( was trying to figure that out for a long time)...

Unfortunately, I will have to use the File/Export... way as the Aircraft directory is totally different from where my .bled files are.

**Comment by tngreene** [comment]
Closing due to actual bug being solved and @arb65912's question being answered.
