### ISSUE TITLE
X-Plane layers not added in new project

### ISSUE THREAD

**Issue by Axel1492** [der-On/XPlane2Blender#296]
Blender: v2.78
X-Plane2Blender: 3.4.0

Error Message:
> Traceback (most recent call last):
>   File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_xplane2blender\xplane_ui.py", line 71, in draw
>     scene_layout(self, scene)
>   File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_xplane2blender\xplane_ui.py", line 166, in scene_layout
>     row.operator('scene.add_xplane_layers')
> UnboundLocalError: local variable 'row' referenced before assignment

If you open an old project there is no problem. But now the "Add XPlane Layers" button is not there anymore and therefore it is impossible to start a new project.

**Comment by tngreene** [comment]
This was fixed in e40dd7da9d86daee3699c98504366b773b61532a

Have you downloaded beta.2 yet?

**Comment by tngreene** [comment]
Closing this due to this being the exact bug description of a problem that was fixed in beta2 Please download it.
