### ISSUE TITLE
Invisible X-Plane object

### ISSUE THREAD

**Issue by myachinyouri** [der-On/XPlane2Blender#305]
File XXXX_sph_radar.blend has been created before updating to XPlane2Blender v3.4.0-beta.5. The object XXXX_sph_radar.obj exported by using XPlane2Blender 3.4.0-beta.5+1.20170922151901 is invisible one in X-Plane 11. However a new Blender object 'untitled.blend' has exported to the 'test_sphere.obj without problem.
[6_files.zip](https://github.com/der-On/XPlane2Blender/files/1327621/6_files.zip)

Resolved! 'Type of active data to display and edit: Material' ---> X-Plane --> Check up the 'Draw Linked Objects' check box which should be ON at 'Draw Settings' menu.

Cheers

**Comment by tngreene** [comment]
I'm a little confused. when you say "Resolved!" Do you mean to say you fixed your own bug?

**Comment by myachinyouri** [comment]
Agree, but I thought the term "Fixed_my_own_bug" just not suitable.
