### ISSUE TITLE
keyframes on armature bones don't export animation commands.

### ISSUE THREAD

**Issue by tkyler** [der-On/XPlane2Blender#310]
With the following hierarchy structure of a simple animated test case (old 2.49 workflow):
[Root_axes]  ----parentOF---->  [bone] ----parentOF --->  [Mesh]
....and key-framing the bone with a simple translation
...and adding a dataref
The object is exported but no animation commands are exported.

The xplane2blender.log output indicates that the armature and animation ARE found, that the keyframes are added, that the dataref is being added....but they never make it to the exported OBJ text file.

<img width="1436" alt="screen shot 2017-10-24 at 5 44 12 pm" src="https://user-images.githubusercontent.com/399085/31971794-0649b9bc-b8e3-11e7-9f77-5940b4c07e56.png">

**Comment by arb65912** [comment]
Hi Tom,
I do not want to mislead you but are you exporting with bone in object mode?
From what I have learned, I use pose mode ( like yours SSs show) to animate object, the I go to bone object mode, enter values for X-Plane for animated keyframes and then export.

**Comment by tkyler** [comment]
so it works when I keyframe the Armature (not the bone-pose).  I thought I had tried this before but guess I missed it.  A bit different form the old 2.49, but definitely workable.

**Comment by arb65912** [comment]
I was told to use pose mode on bones to animate (keyframe as you call it, I might not use proper terminology) objects linked to them.
Linking has to be done in bone pose mode.
Then bone to object mode and input values in Bone properties for X-Plane.
Never used 2.49. Started toying with Blender only about 2 years ago.

**Comment by tkyler** [comment]
I can definitely confirm that if you apply keyframes to a selected bone-pose (when they're blue...the old 2.49 workflow)....the animation commands are not exporting (though the log indicates they probably should) ...but applying keyframes to the Armature (generally orange) does give good exports.  Also, In 2.49, you had to be in bone-pose mode in order to make a mesh a child of a bone....but in 2.78, you simply select 'bone' in the popup menu when CTRL-P.  This definitely saves an annoying step for those used to 2.49.  I think this bug might be more about the discontinuity between the log output and the real output?

**Comment by arb65912** [comment]
I know it sounds funny but for a long time I had a hard time distinguishing between keyframes making animations on timeline and keyframes values entered for X-Plane datarefs but somehow worked out a way to make animations with bones working.

I am sure Ted will make sure that log is consistent with what is exported.

Thanks for the tip on parenting to bone not in pose mode, definitely a time saver.

**Comment by tngreene** [comment]
Can you copy in the part (or a part) of the log you find confusing and then write what you think it should say instead?

**Comment by bsupnik** [comment]
Turns out this is not a bug. If the animation values and datarefs are applied to the bone in question on the bone tab, the animation works.  If they are applied to the dataref section in the data block tab (on the parent armature) they are ignored.
