### ISSUE TITLE
root mode not exporting  (but layers will)

### ISSUE THREAD

**Issue by tkyler** [der-On/XPlane2Blender#311]
This is an old 2.49 file that was opened and saved in 2.78 and cleaned out of everything except a root axes, an animated armature and  a mesh. ...similar setup to issue #310.

The object exports fine in layer mode, but won't export in root mode. (i.e. hit the export button and nothing happens...log output enabled)   Being this is an older file from 2.49, I figure there might something worth looking into.  I have no problem exporting root mode when creating stuff from scratch.  I'm using latest version, 3.4 beta 5 scripts.

Test file attached, but lack of material texture might throw an issue.

[test_root_export.blend.zip](https://github.com/der-On/XPlane2Blender/files/1412862/test_root_export.blend.zip)

FWIW, deleting the root empty in the test file and replacing it with a new one...and reparenting everything else back to it...will cause the root export method to work.

**Comment by tngreene** [comment]
The answer is actually very simple: OBJ is not set to export. In the Root Object's options, if you scroll down, you see in a section called "Advanced Options" a checkbox called "[ ] Export". If it is not checked it will not export.

**Comment by arb65912** [comment]
Hmmm, that is weird as as soon as I click to Root Object's option, Layers Tabs disappear....so there is no Advanced option, only what you see below.
![root object option](https://user-images.githubusercontent.com/16321070/32400033-df4e8292-c0d1-11e7-9055-317ead4840c4.JPG)

**Comment by tngreene** [comment]
Yes, they do disapper from that view. If you create an empty object*, and go to that datablock's properties page you'll see a checkboox that says "root" object.

When checked, the same options  will appear and apply to all child objects of the root objects.

*There is a UI bug where non-empties show the root object mode. I don't think this is intended.

**Comment by arb65912** [comment]
I have created the empty object and parented objects from different layers to it.
It did export but parenting objects in this fashion might not be the most common developing process.

The manual says:"An example use of this workflow is an airplane with many parts. An airplane may have more than 20 parts, and much of them are nestled together making it hard to work on the model without hiding many parts of it. It would be very annoying to have to continually enable and disable the Blender Object Visibility Layers to make each component export which, fortunately, is not necissary in "Root Object" mode. You are free to use that feature of Blender however you wish."

I do not want to post misleading information but I think the most common way of designing is to group main aircraft parts with many subparts into corresponding layers (fuselage, wings, gear...) and export layers as needed.
Mostly after edits/additions to objects on one layer, user would export to see the results.

**Comment by tngreene** [comment]
Every person has said something different to me for how I should suggest to make an airplane. Some say layers mode, some say root objects mode. I might take out the suggestion in the manual entirely or suggest both.
