### ISSUE TITLE
Animations not exporting?

### ISSUE THREAD

**Issue by wiiboy123** [der-On/XPlane2Blender#323]
Hello. I'm trying to export a modified scene of the default 737 with split-scimitar winglets installed, and the animations don't seem to be exporting at all. I'm almost certainly doing something wrong, so I thought I'd ask for assistance here. I imported three OBJs into Blender 2.49 with Xplane2Blender 3.10 and then brought it into Blender 2.79 and made my modifications. Then I selected the armature in pose mode and using the original OBJ file added the dataref path "sim/flightmodel2/wing/wing_tip_deflection_deg[5]" to the armature and assigned values to the keyframes. I've posted a GIF of what my animations tab looks like (I apologize for the resolution). 
![20171224082213-0b6a9d442f gif-2-mp4 com](https://user-images.githubusercontent.com/14097631/34324428-98037b40-e840-11e7-8a9b-ae20764464ec.gif)

When I export the file though, the animations don't turn up at the end of the file like they do in the original. The end of my file looks like this:
![untitled](https://user-images.githubusercontent.com/14097631/34324456-d9082e00-e841-11e7-96f7-b7542c0f2119.png)

Here's my layer panel:
![image](https://user-images.githubusercontent.com/14097631/34324461-09f45084-e842-11e7-8d23-8adad5ca4d47.png)

Blender system info:
[system-info.txt](https://github.com/der-On/XPlane2Blender/files/1584632/system-info.txt)

I'm using Xplane2Blender 3.40rc1.
 
Any insight as to what I'm doing wrong would be greatly, greatly appreciated 😄. If you need any extra information, I'd be glad to supply it to you.

**Comment by airfightergr** [comment]
Have added the dataref at bone tab?
![bone](https://user-images.githubusercontent.com/16308752/34326621-54497600-e8ba-11e7-8442-13c9c856ad37.png)

**Comment by wiiboy123** [comment]
Of course I didn't. I'm guessing the bone tab is for bone animation and the object tab is for object animation. Thanks a lot, the animations are there now! 😃
