### ISSUE TITLE
Add AXIS_KNOB manip from 10.50

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#328]
The AXIS_KNOB manipulator was, for some reason, left out in all this time. Steps needed

1. Add to the datamodel (xplane_props.py) in get_manip_types_for_this_version
2. Add to the UI (<cursor> <min> <max> <click delta> <hold delta> <dataref> <tooltip>)
3. Add to xplane_primitive.py

**Comment by lehthanis** [comment]
@tngreene Hi, I'm just now starting to use XPlane2Blender and I'd really like this functionality as well (converting my model from Max to Blender now)...is there anything I can do to help get this done?

**Comment by tngreene** [comment]
Since we're no longer using the type,type_v1110 pattern adding this should be much easier

**Comment by tngreene** [comment]
@lehthanis, this was added in 5cc0b767e, on the VR branch (see #314). I believe it is stable, but this branch is still in the alpha stage. This was chosen because it affects the same part of the data model it is extending. If you'd like to try using it with your plane you could, but please e-mail me first so I can give you some warnings (ted at x-plane dot com)
