### ISSUE TITLE
Drag Rotate Manipulators throw flags and do not export

### ISSUE THREAD

**Issue by alxunru** [der-On/XPlane2Blender#334]
I'm getting these type of errors using build 7f24a36220dd57e74 on every single use of Drag Rotate manipulators.

"ERROR: Drag Rotate manipulator attached to lever_brake.001 must have at least 2 rotation keyframes that are not the same"
"ERROR: lever_brake.001 is invalid: Drag Rotate manipulators have specific parent-child relationships and animation requirements. See online manipulator documentation for examples."

Ted, there are further report details and associated files sent to your email.
Ben and I can confirm that structurally, the blender file appears to be correct and that there isn't anything strange or weird in the animation set up (the file exports using a different manipulator type).

Please let me know if you need additional resources.

**Comment by tngreene** [comment]
Closing because we fixed it! See #314
