### ISSUE TITLE
Exporter doesn't appear to *not* add useless bones to the XPlaneBone tree

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#335]
In a conversation with @bsupnik, he assumed that the XPlaneBone tree would not contain "useless no-op" bones. When asked what constitutes a no-op bone he indicated things like
- Nested bones with duplicate data
- Bones that have animation but no changes
- Bones that have no meaningful leafs

and other such variations of common sense "does nothing"-ness. He did not know, however, the exact implementation details and I was skeptical.

I investigated the source code and found little evidence of such a feature. It is either buried deeply in the logic of the recursive algorithm used to collect and I can't figure out how to trigger it, or it was once working and is not bugged. Regardless, there is no handy "XPlaneFile.removeNoopBones()" to look at.

## Well researched clues
- XPlaneFile.collectBonesFromBlender(Bones|Objects) repeatedly recurse down, filtering out potential objects who do not have the same parent or the wrong type of parent (see objectFilter and boneFilter inside)
- XPlaneFile.collectBonesFromBlenderObjects is called first from xplane_file's createFilesFromBlender(LayerIndex|RootObject)
- XPlaneFile.collectBlenderObjects filters out any Blender Object that is a convertible (via convertBlenderObject) type
- XPlaneFile.getChildBlenderObjectsForBlenderBone (called from collectBonesFromBlenderBones) filters out any XPlaneObject who doesn't have a bone type, with the right armature and right bone

## Hunches
- I've never seen evidence that the bone tree gets adjusted during the write period

## Questions
- Could bones get skipped during the write portion?

Before I spend more time on this I just want to ask @bsupnik  and @der-On: Is this actually a real thing that the exporter does? Can you provide examples?

**Comment by der-On** [comment]
Currently there is no bone removal algorithm. Actually the artist is in charge of not adding useless Objects/Bones to the stack. The only optimization done is skipping not animated objects and baking theire transformations directly into the pre-animation matrix.

**Comment by tngreene** [comment]
Welp, we have our answer!
