### ISSUE TITLE
ATTR_light_level as custom property gets overriden by material property

### ISSUE THREAD

**Issue by lehthanis** [der-On/XPlane2Blender#343]
In my cockpit I have some knobs on the side console that are lit by a different dataref than the rest of the object, so I wanted to add a custom property for it.  I have the overall light level overriden in the material properties and it seems to place that periodically throughout the obj file...and everywhere I add a custom property (only 5 objects) I have to go in and delete the material property one that appears almost right after it.  It looks like this in the editor:

	# 2 Object: btn_AirCondTemp001
	ANIM_begin
	# static translation
	ANIM_trans	0.32345	-0.09976	3.38899994	0.32345	-0.09976	3.38899994
	# rotation keyframes
	ANIM_rotate_begin	1	0	0	cjs/texanii/manips/environ/temp_control
	ANIM_rotate_key	-1	7.87014865
	ANIM_rotate_key	0	7.87014865
	ANIM_rotate_key	1	7.87014865
	ANIM_rotate_end
	ANIM_rotate_begin	0	1	0	cjs/texanii/manips/environ/temp_control
	ANIM_rotate_key	-1	39.99990321
	ANIM_rotate_key	0	-90.00020741
	ANIM_rotate_key	1	-219.99975113
	ANIM_rotate_end
	# PRIMITIVE: btn_AirCondTemp001	weight: 0
	ATTR_light_level	0 1 sim/cockpit2/electrical/instrument_brightness_ratio[3]
	# MATERIAL: Cockpit_A
	ATTR_light_level	0	1	sim/cockpit2/electrical/instrument_brightness_ratio[2]
	ATTR_manip_command_knob	rotate_large	cjs/texanii/commands/temp_control_knob_up	cjs/texanii/commands/temp_control_knob_down	Temp Control
	TRIS	33612 351
	ANIM_end

the light level without the tabs, instrument_brightness_ratio[3] is the one I have in the custom property slot of the object.  The [2] one is the one that is part of the material properties.

**Comment by airfightergr** [comment]
Fast solution is to make the material single user and apply it to the specific meshes.

**Comment by lehthanis** [comment]
That's not fast at all if I have 412 objects and only 5 of them need a different light source...That means I'd have to select each circuit breaker and assign it the default light level for the material.  Is there a better way?

**Comment by airfightergr** [comment]
You are actually copying the material. You change the copy for the different dataref only. Same texture, same everything. This will have no effect on Substance.

**Comment by lehthanis** [comment]
Ohhh... How do I make that copy and have it use same name?

**Comment by airfightergr** [comment]
![material](https://user-images.githubusercontent.com/16308752/38195042-1ba9acbc-3684-11e8-96f7-21d27a291ecf.png)
By clicking this number, will copy the material and will give a name like "cockpit_obj.001", in this case. You change and assign that to those 5 objects. This is only for X-Plane export.
In substance still you can use the original material or the 001, since both are the same.

**Comment by lehthanis** [comment]
Awesome, thanks! Is there a place jan xplane.org where airplane devs are hanging out these days? The org seems to be pretty dead most of the time.

**Comment by tngreene** [comment]
Thank you to @airfightergr for your awesome community response! Devs helping devs! Always a great thing to see.

**Comment by lehthanis** [comment]
@tngreene I wanted to mention, even though this is closed now...that this did fix my problem for exporting to x-plane but did not change the fact that it generates a new material in the eyes of substance painter.  So technically it is a new material, and the .001 does not mean it's a reference...it's separate.

**Comment by tngreene** [comment]
If you can formulate that in the form of a bug report or feature request, please resubmit that!
