### ISSUE TITLE
XPlane Export Log Error

### ISSUE THREAD

**Issue by ecp2101** [der-On/XPlane2Blender#346]
Hello, I am having trouble exporting from blender using the plugin.

OS: Windows 10, 64bit
Blender version: 2.79
Addon version: 3.40rc

I installed the addon by going to file-user preferences-addons-install addon from file and selecting the io_xplane2blender file. I then attempted to export the stock cube that comes with blender file-export-X-Plane Object.

This is the error message:

XPlane Export Log
         Export produces errors or warnings.
         Please take a look into the Internall text file XPlane2Blender.log

I searched the entire system for the log, but it doesn't exist.

![20180413_154454](https://user-images.githubusercontent.com/38368215/38763571-53f93a24-3f3a-11e8-8fc9-ca425c0ade99.jpg)

**Comment by tngreene** [comment]
Hi. The keywords in the error message are  **internall text file**. Blender has a text editor window, which has a list of internal text files. See [this piece](https://docs.blender.org/manual/en/dev/editors/text_editor.html) of Blender documentation for more.

![location_of_xplane2blender_log](https://user-images.githubusercontent.com/5393207/38770148-201caebe-3fdc-11e8-9b19-090ab12aa9a2.JPG)

You can have this log be written to a text file by going into the XPlane2Blender scene settings, scrolling to the bottom, and enabling Print Debug Info To Output, OBJ, then Create Log File.
![create_log_file](https://user-images.githubusercontent.com/5393207/38770167-7ea1f476-3fdc-11e8-927f-d0958c5993d8.JPG)

The log file will be placed in the same folder as the .blend file.

**Comment by ecp2101** [comment]
Thanks, I figured out the issue and got the plugin to work.

Ethan

On Apr 14, 2018, at 6:12 AM, tngreene <notifications@github.com> wrote:

Hi. The keywords in the error message are *internall text file*. Blender
has a text editor window, which has a list of internal text files. See this
piece <https://docs.blender.org/manual/en/dev/editors/text_editor.html> of
Blender documentation for more.

[image: location_of_xplane2blender_log]
<https://user-images.githubusercontent.com/5393207/38770148-201caebe-3fdc-11e8-9b19-090ab12aa9a2.JPG>

You can have this log be written to a text file by going into the
XPlane2Blender scene settings, scrolling to the bottom, and enabling Print
Debug Info To Output, OBJ, then Create Log File.
[image: create_log_file]
<https://user-images.githubusercontent.com/5393207/38770167-7ea1f476-3fdc-11e8-927f-d0958c5993d8.JPG>

The log file will be placed in the same folder as the .blend file.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/der-On/XPlane2Blender/issues/346#issuecomment-381340132>,
or mute the thread
