### ISSUE TITLE
Document VR manipulators

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#349]
VR manipulators need good documentation on how to construct them! See #314 for more details

**Comment by arb65912** [comment]
As well as regular manipulators in my opinion. (documentation)

**Comment by tngreene** [comment]
Indeed! I have not forgotten about it! Related bugs: #286

**Comment by lehthanis** [comment]
@tngreene I emailed you but it may have gotten lost...I attempted a drag rotate and got a pretty weird error...maybe I'm just confused: Rotation dataref values for the Drag Rotate manipulator attached to GearHandle_A_Front are not in ascending or descending order.

I'm not sure what order is not ascending or descending? So yeah, there's some docs  in the gitbook, but it's missing the example blend file and doesn't really explain the requirements for each manip very well.

**Comment by tngreene** [comment]
Hi @lehthanis ,
Thank you for trying again, yes, I think your e-mail did get burried. Is the link not working for you?

- [Animation Requirements For Smart Manipulators](https://der-on.gitbooks.io/xplane2blender-docs/content/v3.5/indepth/animation_requirements_smart_manipulators.html)
- [example_vr_manipulator_types.zip](https://der-on.gitbooks.io/xplane2blender-docs/content/v3.5/indepth/content/example_vr_manipulator_types.zip)

Its under the section "Further Reading>Example Blend Files".

**Comment by tngreene** [comment]
If it doesn't work for you, here it is again.
[example_vr_manipulator_types.zip](https://github.com/der-On/XPlane2Blender/files/2242656/example_vr_manipulator_types.zip)

**Comment by tngreene** [comment]
To describe more about "not in ascending or descending order", this is an example keyframe table that should trigger this:

Rotation Degrees|Dataref Value
---|---
0 | 0
30 | 5
90 | 1

As you can see, the sequence of Dataref values (0, 5, 1) is not ordered properly. Does that make sense? How are you trying to animate manipulator? And, what parts of the guide do you think are lacking or hard to understand?

**Comment by lehthanis** [comment]
I'll try the download again. I think there may be a problem then because My gear handle has two rotation keyframes, on frame zero the X axis rotation is 10 degrees, and on frame 100 the X rotation is -20 degrees...that's a 30 degree rotation range from handle down in frame zero and up in frame 100.
There's a transform dataref assigned with two keyframes...frame 0 the dataref keyframe value is 1, and frame 100 the dataref keyframe value is 0.
That sounds like it should be ok.

**Comment by lehthanis** [comment]
@tngreene still struggling with this one error...
ERROR: Rotation dataref values for the Drag Rotate manipulator attached to GearHandle_A_Front are not in ascending or descending order.

you can see in the image there's only two keyframes...any thoughts?
https://imgur.com/kivWr9U

**Comment by tngreene** [comment]
That's a very good picture. Could you post another picture of the second frame?

**Comment by lehthanis** [comment]
@tngreene yup, will do, should I open a new issue first?

**Comment by lehthanis** [comment]
@tngreene just in case: here's the other frame: https://imgur.com/7M5lSXh

**Comment by tngreene** [comment]
@lehthanis You've found an actual bug! Thank you! Fortunately it is an easy bug. Moving this conversation #367

**Comment by lehthanis** [comment]
@tngreene YAY!  I'm actually useful!

**Comment by tngreene** [comment]
Here's an issue with gitbooks! The current link to the example gets mangled by some browsers. For instance, (./content/example_vr_manipulator_types.zip) gets turned into (./content/content/content/example_vr_manipulator_types.zip)

Basically no one can use that link. Hence I'm uploading the latest version in this issue, because github's links DO work for people and stick around! This hopefully isn't a permanent solution. Maybe they'll fix their stuff.

[example_vr_manipulator_types.zip](https://github.com/der-On/XPlane2Blender/files/2484383/example_vr_manipulator_types.zip)

**Comment by tngreene** [comment]
Who wants a good tutorial on Axis Detent Ranges? Everybody! What a .blend file we've got. (Now referenced in the manual!) [axis_detent_range_tutorial.zip](https://github.com/der-On/XPlane2Blender/files/2886941/axis_detent_range_tutorial.zip)

**Comment by tngreene** [comment]
- [x] Creating VR manipulators
- [x] Validation rules for VR manipulators
- [x] Using ATTR_manip_keyframe for Drag Rotate Regions
- [x] Covered Axis Detent Ranges and the validation table
- [x] Made some basic examples (__more like very basic__)
- [ ] Put more example use cases online
- [x] Talked about what Autodetect Datarefs does

Good enough for now!
