### ISSUE TITLE
Drag Axis manip type only has two input axes, while DragXY has three.

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#355]
When set to "v11.0" or "v11.1", the manipulators of type "Drag Axis" contain only "Drag X" and "Drag Y" entry fields, while the manipulator of type "Drag XY" contains three.  Shouldn't you be able to drag in any of the 3 axes?

**Comment by tngreene** [comment]
Yes! No data loss has occured. Its just that some properties are being shown when the shouldn't and some are hidden when they shouldn't be. The unit tests didn't catch this because the data is still in here just fine.

**Comment by tngreene** [comment]
Command was also showing Positive Command and Negative Command when it shouldn't. Fixed with 6e32a1fece15e7.
