### ISSUE TITLE
Command manipulators behave strange when they're duplicated

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#356]
So, say you have a plane that has two transponders.  (Such as the Hawk T1).  You want to implement them using command knobs.  If you have only one transponder with the command knob, everything works fine... but the moment you duplicate the command knobs to the second transponder, the manipulators behave differently... their "rotate" cursor becomes single-arrow, instead of double-arrow (Left for the first iteration of the transponder knob, and right arrow for the second iteration), and you can only increase one knob and decrease the other.

(Scroll wheel works fine, though.)

**Comment by alxunru** [comment]
Sounds like the manipulator mesh is being shared across the two knobs (basically making one big manipulator). Turning on mouse click regions in X-Plane should confirm this. When you click on one, both should 'light'. Probably a by product of the exporter merging things with like attributes (which in this case isn't desirable). Do you 'animate' each manipulator mesh with its own animation, or are they static?

**Comment by danklaue** [comment]
Static.

**Comment by bsupnik** [comment]
Alex, I think you're right - we saw this on the S76, and it's really a
design mistake of the OBJ engine, not the exporter - that is, the exporter
can't really do anything to fix this.

Dan, I think there's a dumb work-around: use different tool-tips and the
manipulators will remain separate.

**Comment by tngreene** [comment]
If the exporter can't do anything about it, I'm closing it.
