### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by leecbaker** [der-On/XPlane2Blender#362]
What's the license for XPlane2Blender? It doesn't appear to have a License.txt file in the top directory, nor does it have a license marked on Github.

**Comment by tngreene** [comment]
Good catch! We're choosing one now!

**Comment by tngreene** [comment]
Turns out in __init__.py, which is rarely edited, it a GPL block! Problem solved.

**Comment by tngreene** [comment]
Fixed in 4e26a534768

**Comment by leecbaker** [comment]
Sounds good, thanks!
