### ISSUE TITLE
Show/Hide animations on Empties not being exported (3.5.0-beta2)

### ISSUE THREAD

**Issue by dpospisil** [der-On/XPlane2Blender#377]
Show/Hide animations used to be exported when applied on empties. Whis way it was possible to apply show/hide property on a whole hierarchy of objects.

With 3.5.0-beta2 the Show/Hide animations seem to be ignored on empties.

**Comment by tngreene** [comment]
Quick to debug:

When overriding XPlaneObject.collect, I did not include a call to super().collect()

```python
class XPlaneEmpty(XPlaneObject):
...
    def collect(self):
        super().collect()
        return
```

By forgetting the call to super().collect() we never collect show/hide animations.

Fixed with 081ab9d

**Comment by tngreene** [comment]
Try this build out, see if it works for you too. [io_xplane2blender_3_5_0-dev_0-32_20180823200034.zip](https://github.com/der-On/XPlane2Blender/files/2315982/io_xplane2blender_3_5_0-dev_0-32_20180823200034.zip)

**Comment by dpospisil** [comment]
Verified, works as expected. Many thanks for quick fix!!!
