### ISSUE TITLE
No apparent way to add geometry to LOD in 3.5

### ISSUE THREAD

**Issue by lehthanis** [der-On/XPlane2Blender#388]
I'm using the latest beta 3.5b2 and I'm not seeing any way to add geometry to an LOD.  I can set up the LOD's and their draw ranges in my root object, but I don't see the checkboxes anywhere for specifying which LOD the geometry or parent object belongs to?

This may be an easy thing and I may be dumb for not seeing it, but nobody seems to answer questions anymore at the .org engineering dept forums, so this is the next best thing.

**Comment by tngreene** [comment]
I think you've discovered a bug! Hopefully this is just a case of someone didn't put the right if statement saying "show these LOD boxes at the right time", but I think this will be a simple fix. Then LOD and Root Objects will be working together just fine. Thank you!

**Comment by lehthanis** [comment]
I'm 2 for 2 on "just asking questions", or "I can't figure out how/why" actually turning up bugs!  Awesome!

**Comment by tngreene** [comment]
The good news is I think that there Is a working way to use LODs in Root objects mode: I'll call it the 2.49 way.

1. Make a Root Object
2. In it's obj file settings, set the number of LOD buckets, and the near and far settings for each. Lets say, 3, for instance

LOD Bucket | Near | Far
---------|--------|------
1|0|200
2|200|600
3|600|1000

3. Create your meshes, lights and etc. The Blender Objects you put in Blender Layer 1 will be in LOD bucket 1. The Blender Objects you put in Layer 2 will be in bucket 2, etc.

I'm not sure what will happen to objects that are put in Layers 4-20. They'll probably either be put in all of them, or just the giant bucket at the end. Tell me how it goes!
