### ISSUE TITLE
Decide Old Root Objects LOD work flow vs New Root Objects LOD workflow

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#390]
Recently, trying to help a person understand how to use LODs with root objects mode, I discovered the way to do it was lifted from 2.49:

1. Make your root object
2. Specify the number of LOD buckets you want and their near/far settings
3. Create Child Blender Objects, **make them visible in certain Blender Layers**
4. The Objects in Layers 1 will go in bucket 1. The Objects in Layer 2 will go in bucket 2, etc.

In comparison, to make this more regular with how 2.7x's Layers Mode I propose:
1. Make your root object
2. Specify the number of LOD buckets you want and their near/far settings
3. Create Child Blend Objects, **put them in any dang Blender Layers you want**
4. For each object, set which bucket they go into with the the `object.xplane.lod` checkboxes

The 2.7x Layer's Mode has the benefit that you can use Blender Layers for whatever you want, including organizing objects with the old "Layer as Bucket" mentality. The downside is that for every object, you'll need to specify which LODs they go into.

If we go with the old way, we'll have to document it, or maybe we can make it a bit more apparent. Like, checking the checkboxes also sets their Blender Layer visibility. Or something.

**Comment by lehthanis** [comment]
Is it possible to use parent/child relationships?  For example:

Root Object (2LOD buckets)
--Empty (LOD bucket 1 checked)
----all of the objects with no LOD settings (inherited from LOD1 Empty)
--Empty (LOD bucket 2 checked)
----all of the objects with no LOD settings (inherited from LOD2 Empty)

**Comment by airfightergr** [comment]
@tngreene  I was wondering if you have looked into the upcoming blender 2.8 (beta this October, stable early 2019), which changes completely the layers scheme with collections.
https://code.blender.org/2017/09/view-layers-and-collections/

**Comment by tngreene** [comment]
> 
> 
> Is it possible to use parent/child relationships? For example:
> 
>     * Root Object (2LOD buckets)
> 
>     * * Empty (LOD bucket 1 checked)
> 
>     * * * all of the objects with no LOD settings (inherited from LOD1 Empty)
> 
>     * * Empty (LOD bucket 2 checked)
> 
>     * * * all of the objects with no LOD settings (inherited from LOD2 Empty)

That's a good idea. I'll be thinking of that when I come up with the design. It would certainly reduce the amount of clicking. "Choose parent unless more specific choice is made" is a common pattern.

**Comment by tngreene** [comment]
> 
> 
> @tngreene I was wondering if you have looked into the upcoming blender 2.8 (beta this October, stable early 2019), which changes completely the layers scheme with collections.
> https://code.blender.org/2017/09/view-layers-and-collections/

I have looked at 2.8's new feature list but have no idea how XPlane2Blender is going to be using the new features. 2.8 is probably not going to be supported for some time unless everyone jumps in and says "This is a must!"

**Comment by tngreene** [comment]
@lehthanis I'm pretty sure the parentage set-up you're describing is actually quite do-able, try it out and see what you think.

Given 2.8 is going to have all sorts of new options for us, I'm not going to blow this up unless there is a spec compliance issue.
