### ISSUE TITLE
Support magnetic attach points for VR iPad.

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#412]
Right now, the 
`MAGNET magnet xpad`

function has to be added after the fact.  Wondering if there's a possibility to include it in the XP2B toolset, as a drop-down menu or something. The alternative is, to hack the exported .obj file every time.

(or is it possible to enter it as a custom attribute? If so, how?)

**Comment by tngreene** [comment]
Yes, as you can probably tell from the OBJ spec getting updated the plan is to make it another special Empty type like how the particle emitter is made. It wouldn't be a bad candidate for "good first issue" for anyone that wanted to make a pull request.)

As for being a custom attribute, maybe you could make a mesh object, set it to not draw, and make a custom attribute on that?

**Comment by tngreene** [comment]
This will go nicely with implementing the 2.49 lights conversion. It'll probably be Some Lights, This, Make lights include this. See #400

**Comment by tngreene** [comment]
Calling it closed with 6a2fbb75aefebcd735347a1. The only thing to check with is that this feature is cockpit only. I mean, it makes sense, but, I've been surprised before. Fortunately that is something that is easy to take away.

**Comment by tngreene** [comment]
@danklaue See what this does for you for MAGNET support. To use it, make an Empty, go to it's data tab in the properties editor, change it's special type to "Magnet", put in a debug name and choose xpad and or flashlight.

[io_xplane2blender_3_5_0-dev_0-42_20190316195121.zip](https://github.com/der-On/XPlane2Blender/files/2974431/io_xplane2blender_3_5_0-dev_0-42_20190316195121.zip)

The only thing left to do for this is to fix the bad looking UI for the checkboxes. Maybe we can make them left aligned or something.

**Comment by tngreene** [comment]
If this doesn't work for anyone, tell me. Otherwise, closing!
