### ISSUE TITLE
Feature: Tool for combining Normal Maps with grayscale specmaps

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#51]
Blender can use grayscale specmaps and normals maps. X-Plane uses normal maps with alpha-channel containing specmap. So a tool within blender for combining both would be good, as this process is tedious when doing manually.

**Comment by der-On** [comment]
Use specular texture slot and merge this into the normal texture during runtime. Write the combined texture into new file.

**Comment by bsupnik** [comment]
The compositing rules we want (for now) are:

Specular + Normal:
Normal into RGB, specular into A
Specular only:
Specular into Gray channel, no alpha (PNG _must_ be  gray-scale!)
Normal only:
Normal into RGB, no alpha (PNG _must_ be RGB color)

**Comment by der-On** [comment]
@bsupnik we currently cannot deal with the specular only and the normal only cases, as blender always converts images into RGBA internally so we have no way of detecting if an image has an alpha channel or not. Saving images  in Grayscale or RGB is possible (with a tiny hack) however.

**Comment by der-On** [comment]
Update 2: I haven't considered DDS textures yet. I'm not sure if Blender can write DDS. Eventually we'll need an external cross-platform tool to convert the generated PNGs to DDS.

**Comment by bsupnik** [comment]
X-Plane does not currently support normal maps in DDS, so not having tool support is okay.

I'm not sure I understand the RGBA issues - the output write format should be a function of whether the maps exist _at all_ in the material editor.

**Comment by der-On** [comment]
### Optimize texture (re)compilation:

1. check if there is a compiled texture already
2. if there is no compiled texture: compile
3. if the mod-date of the source texture is older: skip compilation
4. if the mod-date of the source texture is younger: compile

### Opimize pixel reading and writing

Instead of using setPixel() and getPixel() read and write pixels more efficient in loops, preventing multiple multiplications for each pixel operation and turning them into cheap additions.
