### ISSUE TITLE
Nested animations still don't work 100% reliably

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#72]
When parenting an already animated object to an animated bone, the resulting movement in X-Plane is twisted mayhem.

Making an "in-between" piece (i.e. parenting the first object to a different object, before parenting that in-between object to the bone) yields slightly more predictable results, although orientation of object is still offset by 90º.

**Comment by bsupnik** [comment]
@danklaue  This bug was one we tried to fix in the 3-3 scripts.  

Can you please re-try this case in 3-3 and attach a .blend file that fails to WYSIWYG animate if it is still broken?

Thanks
Ben

**Comment by danklaue** [comment]
OK, this one works now.
