### ISSUE TITLE
Remove the custom profiler and use Python profiler instead

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#74]

**Comment by tngreene** [comment]
It appears that XPlaneProfiler is completely unused. Is this still a feature requested? Or even used?

**Comment by bsupnik** [comment]
I'm okay to nuke it.

**Comment by tngreene** [comment]
Nuke which part? The unsued profiler code? The idea of having a profiler? The idea of using the Python profiler?

**Comment by bsupnik** [comment]
Sorry, I'm okay to nuke the XPlaneProfiler (e.g. the custom code designed to be a perf tool).

**Comment by tngreene** [comment]
Bug #318 is a better description of the problem. Close'd!
